//! Generated by `cargo xtask qmi-table`; do not edit.
//!
//! Source: https://raw.githubusercontent.com/torvalds/linux/master/drivers/net/usb/qmi_wwan.c

use super::discovery::QmiEntry;

/// Number of `products[]` entries.
pub const COUNT: usize = 446;

/// `products[]` entries of the kernel's QMI WWAN driver.
pub const ENTRIES: [QmiEntry; COUNT] = [
    // 1. CDC ECM like devices match on the control interface
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x09, false), // Huawei E392, E398 and possibly others sharing both device id and more...
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x39, false), // Vodafone/Huawei K5005 (12d1:14c8) and similar modems
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x69, false), // HUAWEI_INTERFACE_NDIS_CONTROL_QUALCOMM
    QmiEntry::class(0x22b8, None, 0xff, 0xfb, 0xff, false), // Motorola Mapphone devices with MDM6600
    // 2. Combined interface devices matching on class+protocol
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x07, false), // Huawei E367 and possibly others in "Windows mode"
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x11, false), // Huawei E392, E398 and possibly others in "Windows mode"
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x37, false), // HUAWEI_NDIS_SINGLE_INTERFACE_VDF
    QmiEntry::class(0x12d1, None, 0xff, 0x01, 0x67, false), // HUAWEI_INTERFACE_NDIS_HW_QUALCOMM
    QmiEntry::class(0x106c, None, 0xff, 0xf0, 0xff, false), // Pantech UML290, P4200 and more
    QmiEntry::class(0x106c, None, 0xff, 0xf1, 0xff, false), // Pantech UML290 - newer firmware
    QmiEntry::class(0x1410, Some(0xb001), 0x02, 0x06, 0x00, false), // Novatel USB551L and MC551
    QmiEntry::class(0x1410, Some(0x9010), 0x02, 0x06, 0x00, false), // Novatel E362
    QmiEntry::class(0x1410, Some(0x9011), 0x02, 0x06, 0x00, false), // Novatel Expedite E371
    QmiEntry::class(0x413c, Some(0x8195), 0x02, 0x06, 0x00, false), // Dell Wireless 5800 (Novatel E362)
    QmiEntry::class(0x413c, Some(0x8196), 0x02, 0x06, 0x00, false), // Dell Wireless 5800 V2 (Novatel E362)
    QmiEntry::class(0x413c, Some(0x819b), 0x02, 0x06, 0x00, false), // Dell Wireless 5804 (Novatel E371)
    QmiEntry::class(0x16d5, Some(0x650a), 0x02, 0x06, 0x00, false), // ADU960S
    QmiEntry::class(0x03f0, Some(0x421d), 0x02, 0x06, 0x00, false), // HP lt2523 (Novatel E371)
    QmiEntry::class(0x03f0, Some(0x581d), 0xff, 0x01, 0x07, false), // HP lt4112 LTE/HSPA+ Gobi 4G Module (Huawei me906e)
    QmiEntry::class(0x2c7c, Some(0x0122), 0xff, 0xff, 0xff, true),  // Quectel RG650V
    QmiEntry::class(0x2c7c, Some(0x0125), 0xff, 0xff, 0xff, true), // Quectel EC25, EC20 R2.0  Mini PCIe
    QmiEntry::class(0x2c7c, Some(0x013d), 0xff, 0xff, 0xff, true), // Quectel RG660QB
    QmiEntry::class(0x2c7c, Some(0x0306), 0xff, 0xff, 0xff, true), // Quectel EP06/EG06/EM06
    QmiEntry::class(0x2c7c, Some(0x0512), 0xff, 0xff, 0xff, true), // Quectel EG12/EM12
    QmiEntry::class(0x2c7c, Some(0x0620), 0xff, 0xff, 0xff, true), // Quectel EM160R-GL
    QmiEntry::class(0x2c7c, Some(0x0800), 0xff, 0xff, 0xff, true), // Quectel RM500Q-GL
    QmiEntry::class(0x2c7c, Some(0x0801), 0xff, 0xff, 0xff, true), // Quectel RM520N
    // 3. Combined interface devices matching on interface number
    QmiEntry::interface(0x0408, Some(0xea42), 4, false), // Yota / Megafon M100-1
    QmiEntry::interface(0x05c6, Some(0x6001), 3, false), // 4G LTE usb-modem U901
    QmiEntry::interface(0x05c6, Some(0x7000), 0, false),
    QmiEntry::interface(0x05c6, Some(0x7001), 1, false),
    QmiEntry::interface(0x05c6, Some(0x7002), 1, false),
    QmiEntry::interface(0x05c6, Some(0x7101), 1, false),
    QmiEntry::interface(0x05c6, Some(0x7101), 2, false),
    QmiEntry::interface(0x05c6, Some(0x7101), 3, false),
    QmiEntry::interface(0x05c6, Some(0x7102), 1, false),
    QmiEntry::interface(0x05c6, Some(0x7102), 2, false),
    QmiEntry::interface(0x05c6, Some(0x7102), 3, false),
    QmiEntry::interface(0x05c6, Some(0x8000), 7, false),
    QmiEntry::interface(0x05c6, Some(0x8001), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9000), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9003), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9005), 2, false),
    QmiEntry::interface(0x05c6, Some(0x900a), 4, false),
    QmiEntry::interface(0x05c6, Some(0x900b), 2, false),
    QmiEntry::interface(0x05c6, Some(0x900c), 4, false),
    QmiEntry::interface(0x05c6, Some(0x900c), 5, false),
    QmiEntry::interface(0x05c6, Some(0x900c), 6, false),
    QmiEntry::interface(0x05c6, Some(0x900d), 5, false),
    QmiEntry::interface(0x05c6, Some(0x900f), 3, false),
    QmiEntry::interface(0x05c6, Some(0x900f), 4, false),
    QmiEntry::interface(0x05c6, Some(0x900f), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9010), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9010), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9011), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9011), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9021), 1, false),
    QmiEntry::interface(0x05c6, Some(0x9022), 2, false),
    QmiEntry::interface(0x05c6, Some(0x9025), 4, true), // Alcatel-sbell ASB TL131 TDD LTE (China Mobile)
    QmiEntry::interface(0x05c6, Some(0x9026), 3, false),
    QmiEntry::interface(0x05c6, Some(0x902e), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9031), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9032), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9033), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9033), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9033), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9033), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9034), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9034), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9034), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9034), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9034), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9035), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9036), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9037), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9038), 4, false),
    QmiEntry::interface(0x05c6, Some(0x903b), 7, false),
    QmiEntry::interface(0x05c6, Some(0x903c), 6, false),
    QmiEntry::interface(0x05c6, Some(0x903d), 6, false),
    QmiEntry::interface(0x05c6, Some(0x903e), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9043), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9046), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9046), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9046), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9047), 2, false),
    QmiEntry::interface(0x05c6, Some(0x9047), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9047), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9048), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9048), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9048), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9048), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9048), 8, false),
    QmiEntry::interface(0x05c6, Some(0x904c), 5, false),
    QmiEntry::interface(0x05c6, Some(0x904c), 6, false),
    QmiEntry::interface(0x05c6, Some(0x904c), 7, false),
    QmiEntry::interface(0x05c6, Some(0x904c), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9050), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9052), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9053), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9053), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9054), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9054), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9055), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9055), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9055), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9055), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9055), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9056), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 2, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9062), 9, false),
    QmiEntry::interface(0x05c6, Some(0x9064), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9065), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9065), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9066), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9066), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9067), 1, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 2, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9068), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9069), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9069), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9069), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9069), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9070), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9070), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9075), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9076), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9076), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9076), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9076), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9076), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9077), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9077), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9077), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9077), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9078), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9079), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9079), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9079), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9079), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9079), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9080), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9080), 6, false),
    QmiEntry::interface(0x05c6, Some(0x9080), 7, false),
    QmiEntry::interface(0x05c6, Some(0x9080), 8, false),
    QmiEntry::interface(0x05c6, Some(0x9083), 3, false),
    QmiEntry::interface(0x05c6, Some(0x9084), 4, false),
    QmiEntry::interface(0x05c6, Some(0x9091), 2, true), // Compal RXM-G1
    QmiEntry::interface(0x05c6, Some(0x90b2), 3, false), // ublox R410M
    QmiEntry::interface(0x05c6, Some(0x90db), 2, true), // Compal RXM-G1
    QmiEntry::interface(0x05c6, Some(0x920d), 0, false),
    QmiEntry::interface(0x05c6, Some(0x920d), 5, false),
    QmiEntry::interface(0x05c6, Some(0x9625), 4, true), // YUGA CLM920-NC5
    QmiEntry::interface(0x0846, Some(0x68a2), 8, false),
    QmiEntry::interface(0x0846, Some(0x68d3), 8, false), // Netgear Aircard 779S
    QmiEntry::interface(0x12d1, Some(0x140c), 1, false), // Huawei E173
    QmiEntry::interface(0x12d1, Some(0x14ac), 1, false), // Huawei E1820
    QmiEntry::interface(0x1435, Some(0x0918), 3, false), // Wistron NeWeb D16Q1
    QmiEntry::interface(0x1435, Some(0x0918), 4, false), // Wistron NeWeb D16Q1
    QmiEntry::interface(0x1435, Some(0x0918), 5, false), // Wistron NeWeb D16Q1
    QmiEntry::interface(0x1435, Some(0x3185), 4, false), // Wistron NeWeb M18Q5
    QmiEntry::interface(0x1435, Some(0xd111), 4, false), // M9615A DM11-1 D51QC
    QmiEntry::interface(0x1435, Some(0xd181), 3, false), // Wistron NeWeb D18Q1
    QmiEntry::interface(0x1435, Some(0xd181), 4, false), // Wistron NeWeb D18Q1
    QmiEntry::interface(0x1435, Some(0xd181), 5, false), // Wistron NeWeb D18Q1
    QmiEntry::interface(0x1435, Some(0xd182), 4, false), // Wistron NeWeb D18
    QmiEntry::interface(0x1435, Some(0xd182), 5, false), // Wistron NeWeb D18
    QmiEntry::interface(0x1435, Some(0xd191), 4, false), // Wistron NeWeb D19Q1
    QmiEntry::interface(0x1508, Some(0x1001), 4, true),  // Fibocom NL668 series
    QmiEntry::interface(0x1690, Some(0x7588), 4, false), // ASKEY WWHC050
    QmiEntry::interface(0x16d8, Some(0x6003), 0, false), // CMOTech 6003
    QmiEntry::interface(0x16d8, Some(0x6007), 0, false), // CMOTech CHE-628S
    QmiEntry::interface(0x16d8, Some(0x6008), 0, false), // CMOTech CMU-301
    QmiEntry::interface(0x16d8, Some(0x6280), 0, false), // CMOTech CHU-628
    QmiEntry::interface(0x16d8, Some(0x7001), 0, false), // CMOTech CHU-720S
    QmiEntry::interface(0x16d8, Some(0x7002), 0, false), // CMOTech 7002
    QmiEntry::interface(0x16d8, Some(0x7003), 4, false), // CMOTech CHU-629K
    QmiEntry::interface(0x16d8, Some(0x7004), 3, false), // CMOTech 7004
    QmiEntry::interface(0x16d8, Some(0x7006), 5, false), // CMOTech CGU-629
    QmiEntry::interface(0x16d8, Some(0x700a), 4, false), // CMOTech CHU-629S
    QmiEntry::interface(0x16d8, Some(0x7211), 0, false), // CMOTech CHU-720I
    QmiEntry::interface(0x16d8, Some(0x7212), 0, false), // CMOTech 7212
    QmiEntry::interface(0x16d8, Some(0x7213), 0, false), // CMOTech 7213
    QmiEntry::interface(0x16d8, Some(0x7251), 1, false), // CMOTech 7251
    QmiEntry::interface(0x16d8, Some(0x7252), 1, false), // CMOTech 7252
    QmiEntry::interface(0x16d8, Some(0x7253), 1, false), // CMOTech 7253
    QmiEntry::interface(0x19d2, Some(0x0002), 1, false),
    QmiEntry::interface(0x19d2, Some(0x0012), 1, false),
    QmiEntry::interface(0x19d2, Some(0x0017), 3, false),
    QmiEntry::interface(0x19d2, Some(0x0019), 3, false), // ONDA MT689DC
    QmiEntry::interface(0x19d2, Some(0x0021), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0025), 1, false),
    QmiEntry::interface(0x19d2, Some(0x0031), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0042), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0049), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0052), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0055), 1, false), // ZTE (Vodafone) K3520-Z
    QmiEntry::interface(0x19d2, Some(0x0058), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0063), 4, false), // ZTE (Vodafone) K3565-Z
    QmiEntry::interface(0x19d2, Some(0x0104), 4, false), // ZTE (Vodafone) K4505-Z
    QmiEntry::interface(0x19d2, Some(0x0113), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0118), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0121), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0123), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0124), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0125), 6, false),
    QmiEntry::interface(0x19d2, Some(0x0126), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0130), 1, false),
    QmiEntry::interface(0x19d2, Some(0x0133), 3, false),
    QmiEntry::interface(0x19d2, Some(0x0141), 5, false),
    QmiEntry::interface(0x19d2, Some(0x0157), 5, false), // ZTE MF683
    QmiEntry::interface(0x19d2, Some(0x0158), 3, false),
    QmiEntry::interface(0x19d2, Some(0x0167), 4, false), // ZTE MF820D
    QmiEntry::interface(0x19d2, Some(0x0168), 4, false),
    QmiEntry::interface(0x19d2, Some(0x0176), 3, false),
    QmiEntry::interface(0x19d2, Some(0x0178), 3, false),
    QmiEntry::interface(0x19d2, Some(0x0189), 4, false), // ZTE MF290
    QmiEntry::interface(0x19d2, Some(0x0191), 4, false), // ZTE EuFi890
    QmiEntry::interface(0x19d2, Some(0x0199), 1, false), // ZTE MF820S
    QmiEntry::interface(0x19d2, Some(0x0200), 1, false),
    QmiEntry::interface(0x19d2, Some(0x0257), 3, false), // ZTE MF821
    QmiEntry::interface(0x19d2, Some(0x0265), 4, false), // ONDA MT8205 4G LTE
    QmiEntry::interface(0x19d2, Some(0x0284), 4, false), // ZTE MF880
    QmiEntry::interface(0x19d2, Some(0x0326), 4, false), // ZTE MF821D
    QmiEntry::interface(0x19d2, Some(0x0396), 3, false), // ZTE ZM8620
    QmiEntry::interface(0x19d2, Some(0x0412), 4, false), // Telewell TW-LTE 4G
    QmiEntry::interface(0x19d2, Some(0x1008), 4, false), // ZTE (Vodafone) K3570-Z
    QmiEntry::interface(0x19d2, Some(0x1010), 4, false), // ZTE (Vodafone) K3571-Z
    QmiEntry::interface(0x19d2, Some(0x1012), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1018), 3, false), // ZTE (Vodafone) K5006-Z
    QmiEntry::interface(0x19d2, Some(0x1021), 2, false),
    QmiEntry::interface(0x19d2, Some(0x1245), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1247), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1252), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1254), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1255), 3, false),
    QmiEntry::interface(0x19d2, Some(0x1255), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1256), 4, false),
    QmiEntry::interface(0x19d2, Some(0x1270), 5, false), // ZTE MF667
    QmiEntry::interface(0x19d2, Some(0x1275), 3, false), // ZTE P685M
    QmiEntry::interface(0x19d2, Some(0x1401), 2, false),
    QmiEntry::interface(0x19d2, Some(0x1402), 2, false), // ZTE MF60
    QmiEntry::interface(0x19d2, Some(0x1424), 2, false),
    QmiEntry::interface(0x19d2, Some(0x1425), 2, false),
    QmiEntry::interface(0x19d2, Some(0x1426), 2, false), // ZTE MF91
    QmiEntry::interface(0x19d2, Some(0x1428), 2, false), // Telewell TW-LTE 4G v2
    QmiEntry::interface(0x19d2, Some(0x1432), 3, false), // ZTE ME3620
    QmiEntry::interface(0x19d2, Some(0x1485), 5, false), // ZTE MF286D
    QmiEntry::interface(0x19d2, Some(0x2002), 4, false), // ZTE (Vodafone) K3765-Z
    QmiEntry::interface(0x2001, Some(0x7e16), 3, false), // D-Link DWM-221
    QmiEntry::interface(0x2001, Some(0x7e19), 4, false), // D-Link DWM-221 B1
    QmiEntry::interface(0x2001, Some(0x7e35), 4, false), // D-Link DWM-222
    QmiEntry::interface(0x2001, Some(0x7e3d), 4, false), // D-Link DWM-222 A2
    QmiEntry::interface(0x2020, Some(0x2031), 4, false), // Olicard 600
    QmiEntry::interface(0x2020, Some(0x2033), 4, false), // BroadMobi BM806U
    QmiEntry::interface(0x2020, Some(0x2060), 4, true),  // BroadMobi BM818
    QmiEntry::interface(0x0f3d, Some(0x68a2), 8, false), // Sierra Wireless MC7700
    QmiEntry::interface(0x114f, Some(0x68a2), 8, false), // Sierra Wireless MC7750
    QmiEntry::interface(0x1199, Some(0x68a2), 8, false), // Sierra Wireless MC7710 in QMI mode
    QmiEntry::interface(0x1199, Some(0x68a2), 19, false), // Sierra Wireless MC7710 in QMI mode
    QmiEntry::interface(0x1199, Some(0x68c0), 8, true),  // Sierra Wireless MC7304/MC7354, WP76xx
    QmiEntry::interface(0x1199, Some(0x68c0), 10, true), // Sierra Wireless MC7304/MC7354
    QmiEntry::interface(0x1199, Some(0x901c), 8, false), // Sierra Wireless EM7700
    QmiEntry::interface(0x1199, Some(0x901f), 8, false), // Sierra Wireless EM7355
    QmiEntry::interface(0x1199, Some(0x9041), 8, false), // Sierra Wireless MC7305/MC7355
    QmiEntry::interface(0x1199, Some(0x9041), 10, false), // Sierra Wireless MC7305/MC7355
    QmiEntry::interface(0x1199, Some(0x9051), 8, false), // Netgear AirCard 340U
    QmiEntry::interface(0x1199, Some(0x9053), 8, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x9054), 8, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x9055), 8, false), // Netgear AirCard 341U
    QmiEntry::interface(0x1199, Some(0x9056), 8, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x9057), 8, false),
    QmiEntry::interface(0x1199, Some(0x9061), 8, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x9063), 8, false), // Sierra Wireless EM7305
    QmiEntry::interface(0x1199, Some(0x9063), 10, false), // Sierra Wireless EM7305
    QmiEntry::interface(0x1199, Some(0x9071), 8, true),  // Sierra Wireless MC74xx
    QmiEntry::interface(0x1199, Some(0x9071), 10, true), // Sierra Wireless MC74xx
    QmiEntry::interface(0x1199, Some(0x9079), 8, true),  // Sierra Wireless EM74xx
    QmiEntry::interface(0x1199, Some(0x9079), 10, true), // Sierra Wireless EM74xx
    QmiEntry::interface(0x1199, Some(0x907b), 8, true),  // Sierra Wireless EM74xx
    QmiEntry::interface(0x1199, Some(0x907b), 10, true), // Sierra Wireless EM74xx
    QmiEntry::interface(0x1199, Some(0x9091), 8, true),  // Sierra Wireless EM7565
    QmiEntry::interface(0x1199, Some(0xc081), 8, true),  // Sierra Wireless EM7590
    QmiEntry::interface(0x1bbb, Some(0x011e), 4, false), // Telekom Speedstick LTE II (Alcatel One Touch L100V LTE)
    QmiEntry::interface(0x1bbb, Some(0x0203), 2, false), // Alcatel L800MA
    QmiEntry::interface(0x2357, Some(0x0201), 4, false), // TP-LINK HSUPA Modem MA180
    QmiEntry::interface(0x2357, Some(0x9000), 4, false), // TP-LINK MA260
    QmiEntry::interface(0x1bc7, Some(0x0991), 0, true),  // Telit FE990D50
    QmiEntry::interface(0x1bc7, Some(0x1031), 3, true),  // Telit LE910C1-EUX
    QmiEntry::interface(0x1bc7, Some(0x1034), 2, true),  // Telit LE910C4-WWX
    QmiEntry::interface(0x1bc7, Some(0x1037), 4, true),  // Telit LE910C4-WWX
    QmiEntry::interface(0x1bc7, Some(0x1038), 3, true),  // Telit LE910C4-WWX
    QmiEntry::interface(0x1bc7, Some(0x103a), 0, true),  // Telit LE910C4-WWX
    QmiEntry::interface(0x1bc7, Some(0x1040), 2, true),  // Telit LE922A
    QmiEntry::interface(0x1bc7, Some(0x1050), 2, true),  // Telit FN980
    QmiEntry::interface(0x1bc7, Some(0x1057), 2, true),  // Telit FN980
    QmiEntry::interface(0x1bc7, Some(0x1060), 2, true),  // Telit LN920
    QmiEntry::interface(0x1bc7, Some(0x1070), 2, true),  // Telit FN990A
    QmiEntry::interface(0x1bc7, Some(0x1077), 2, true),  // Telit FN990A w/audio
    QmiEntry::interface(0x1bc7, Some(0x1080), 2, true),  // Telit FE990A
    QmiEntry::interface(0x1bc7, Some(0x10a0), 0, true),  // Telit FN920C04
    QmiEntry::interface(0x1bc7, Some(0x10a4), 0, true),  // Telit FN920C04
    QmiEntry::interface(0x1bc7, Some(0x10a9), 0, true),  // Telit FN920C04
    QmiEntry::interface(0x1bc7, Some(0x10b0), 0, true),  // Telit FE990B
    QmiEntry::interface(0x1bc7, Some(0x10c0), 0, true),  // Telit FE910C04
    QmiEntry::interface(0x1bc7, Some(0x10c4), 0, true),  // Telit FE910C04
    QmiEntry::interface(0x1bc7, Some(0x10c8), 0, true),  // Telit FE910C04
    QmiEntry::interface(0x1bc7, Some(0x10d0), 0, true),  // Telit FN990B
    QmiEntry::interface(0x1bc7, Some(0x1100), 3, false), // Telit ME910
    QmiEntry::interface(0x1bc7, Some(0x1101), 3, false), // Telit ME910 dual modem
    QmiEntry::interface(0x1bc7, Some(0x1200), 5, false), // Telit LE920
    QmiEntry::interface(0x1bc7, Some(0x1201), 2, true),  // Telit LE920, LE920A4
    QmiEntry::interface(0x1bc7, Some(0x1230), 2, true),  // Telit LE910Cx
    QmiEntry::interface(0x1bc7, Some(0x1250), 0, true),  // Telit LE910Cx
    QmiEntry::interface(0x1bc7, Some(0x1260), 2, true),  // Telit LE910Cx
    QmiEntry::interface(0x1bc7, Some(0x1261), 2, true),  // Telit LE910Cx
    QmiEntry::interface(0x1bc7, Some(0x1900), 1, true),  // Telit LN940 series
    QmiEntry::interface(0x1bc7, Some(0x3000), 0, true),  // Telit FN912 series
    QmiEntry::interface(0x1bc7, Some(0x3001), 0, true),  // Telit FN912 series
    QmiEntry::interface(0x1c9e, Some(0x9801), 3, false), // Telewell TW-3G HSPA+
    QmiEntry::interface(0x1c9e, Some(0x9803), 4, false), // Telewell TW-3G HSPA+
    QmiEntry::interface(0x1c9e, Some(0x9b01), 3, false), // XS Stick W100-2 from 4G Systems
    QmiEntry::interface(0x1c9e, Some(0x9b05), 4, true),  // Longsung U8300
    QmiEntry::interface(0x1c9e, Some(0x9b3c), 4, true),  // Longsung U9300
    QmiEntry::interface(0x0b3c, Some(0xc000), 4, false), // Olivetti Olicard 100
    QmiEntry::interface(0x0b3c, Some(0xc001), 4, false), // Olivetti Olicard 120
    QmiEntry::interface(0x0b3c, Some(0xc002), 4, false), // Olivetti Olicard 140
    QmiEntry::interface(0x0b3c, Some(0xc004), 6, false), // Olivetti Olicard 155
    QmiEntry::interface(0x0b3c, Some(0xc005), 6, false), // Olivetti Olicard 200
    QmiEntry::interface(0x0b3c, Some(0xc00a), 6, false), // Olivetti Olicard 160
    QmiEntry::interface(0x0b3c, Some(0xc00b), 4, false), // Olivetti Olicard 500
    QmiEntry::interface(0x1e2d, Some(0x0060), 4, false), // Cinterion PLxx
    QmiEntry::interface(0x1e2d, Some(0x006f), 8, true),  // Cinterion PLS83/PLS63
    QmiEntry::interface(0x1e2d, Some(0x0053), 4, false), // Cinterion PHxx,PXxx
    QmiEntry::interface(0x1e2d, Some(0x0063), 10, false), // Cinterion ALASxx (1 RmNet)
    QmiEntry::interface(0x1e2d, Some(0x0082), 4, false), // Cinterion PHxx,PXxx (2 RmNet)
    QmiEntry::interface(0x1e2d, Some(0x0082), 5, false), // Cinterion PHxx,PXxx (2 RmNet)
    QmiEntry::interface(0x1e2d, Some(0x0083), 4, false), // Cinterion PHxx,PXxx (1 RmNet + USB Audio)
    QmiEntry::interface(0x1e2d, Some(0x00b0), 4, true),  // Cinterion CLS8
    QmiEntry::interface(0x1e2d, Some(0x00b7), 0, false), // Cinterion MV31 RmNet
    QmiEntry::interface(0x1e2d, Some(0x00b9), 0, false), // Cinterion MV31 RmNet based on new baseline
    QmiEntry::interface(0x1e2d, Some(0x00f3), 0, false), // Cinterion MV32-W-A RmNet
    QmiEntry::interface(0x1e2d, Some(0x00f4), 0, false), // Cinterion MV32-W-B RmNet
    QmiEntry::interface(0x413c, Some(0x81a2), 8, false), // Dell Wireless 5806 Gobi(TM) 4G LTE Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81a3), 8, false), // Dell Wireless 5570 HSPA+ (42Mbps) Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81a4), 8, false), // Dell Wireless 5570e HSPA+ (42Mbps) Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81a8), 8, false), // Dell Wireless 5808 Gobi(TM) 4G LTE Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81a9), 8, false), // Dell Wireless 5808e Gobi(TM) 4G LTE Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81b1), 8, false), // Dell Wireless 5809e Gobi(TM) 4G LTE Mobile Broadband Card
    QmiEntry::interface(0x413c, Some(0x81b3), 8, false), // Dell Wireless 5809e Gobi(TM) 4G LTE Mobile Broadband Card (rev3)
    QmiEntry::interface(0x413c, Some(0x81b6), 8, false), // Dell Wireless 5811e
    QmiEntry::interface(0x413c, Some(0x81b6), 10, false), // Dell Wireless 5811e
    QmiEntry::interface(0x413c, Some(0x81c2), 8, false), // Dell Wireless 5811e
    QmiEntry::interface(0x413c, Some(0x81cc), 8, false), // Dell Wireless 5816e
    QmiEntry::interface(0x413c, Some(0x81d7), 0, false), // Dell Wireless 5821e
    QmiEntry::interface(0x413c, Some(0x81d7), 1, false), // Dell Wireless 5821e preproduction config
    QmiEntry::interface(0x413c, Some(0x81e0), 0, false), // Dell Wireless 5821e with eSIM support
    QmiEntry::interface(0x413c, Some(0x81e4), 0, false), // Dell Wireless 5829e with eSIM support
    QmiEntry::interface(0x413c, Some(0x81e6), 0, false), // Dell Wireless 5829e
    QmiEntry::interface(0x03f0, Some(0x4e1d), 8, false), // HP lt4111 LTE/EV-DO/HSPA+ Gobi 4G Module
    QmiEntry::interface(0x03f0, Some(0x9d1d), 1, false), // HP lt4120 Snapdragon X5 LTE
    QmiEntry::interface(0x22de, Some(0x9051), 2, true),  // Hucom Wireless HM-211S/K
    QmiEntry::interface(0x22de, Some(0x9061), 3, false), // WeTelecom WPD-600N
    QmiEntry::interface(0x1e0e, Some(0x9001), 5, true),  // SIMCom 7100E, 7230E, 7600E ++
    QmiEntry::interface(0x1e0e, Some(0x9071), 3, true),  // SIMCom 8230C ++
    QmiEntry::interface(0x2c7c, Some(0x0121), 4, true),  // Quectel EC21 Mini PCIe
    QmiEntry::interface(0x2c7c, Some(0x0191), 4, true),  // Quectel EG91
    QmiEntry::interface(0x2c7c, Some(0x0195), 4, true),  // Quectel EG95
    QmiEntry::interface(0x2c7c, Some(0x0296), 4, false), // Quectel BG96
    QmiEntry::interface(0x2c7c, Some(0x030e), 4, true),  // Quectel EM05GV2
    QmiEntry::interface(0x2c7c, Some(0x0316), 3, true),  // Quectel RG255C
    QmiEntry::interface(0x2cb7, Some(0x0104), 4, true),  // Fibocom NL678 series
    QmiEntry::interface(0x2cb7, Some(0x0112), 0, true),  // Fibocom FG132
    QmiEntry::interface(0x04b7, Some(0x8217), 8, true),  // Compal EXM-G1x
    QmiEntry::interface(0x0489, Some(0xe0b4), 0, false), // Foxconn T77W968 LTE
    QmiEntry::interface(0x0489, Some(0xe0b5), 0, false), // Foxconn T77W968 LTE with eSIM support
    QmiEntry::interface(0x2692, Some(0x9025), 4, false), // Cellient MPL200 (rebranded Qualcomm 05c6:9025)
    QmiEntry::interface(0x1546, Some(0x1312), 4, true),  // u-blox LARA-R6 01B
    QmiEntry::interface(0x1546, Some(0x1342), 4, true),  // u-blox LARA-L6
    QmiEntry::interface(0x33f8, Some(0x0104), 4, true),  // Rolling RW101 RMNET
    QmiEntry::interface(0x2dee, Some(0x4d22), 5, false), // MeiG Smart SRM825L
    QmiEntry::interface(0x2dee, Some(0x4d63), 0, true),  // MeiG SRM813Q w/ Modem(PPP)
    QmiEntry::interface(0x2dee, Some(0x4d64), 0, true),  // MeiG SRM813Q w/ NMEA
    // 4. Gobi 1000 devices
    QmiEntry::interface(0x05c6, Some(0x9212), 3, false), // Acer Gobi Modem Device
    QmiEntry::interface(0x03f0, Some(0x1f1d), 3, false), // HP un2400 Gobi Modem Device
    QmiEntry::interface(0x04da, Some(0x250d), 3, false), // Panasonic Gobi Modem device
    QmiEntry::interface(0x413c, Some(0x8172), 3, false), // Dell Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa001), 3, false), // Novatel/Verizon USB-1000
    QmiEntry::interface(0x1410, Some(0xa002), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa003), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa004), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa005), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa006), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x1410, Some(0xa007), 3, false), // Novatel Gobi Modem device
    QmiEntry::interface(0x0b05, Some(0x1776), 3, false), // Asus Gobi Modem device
    QmiEntry::interface(0x19d2, Some(0xfff3), 3, false), // ONDA Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9001), 3, false), // Generic Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9002), 3, false), // Generic Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9202), 3, false), // Generic Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9203), 3, false), // Generic Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9222), 3, false), // Generic Gobi Modem device
    QmiEntry::interface(0x05c6, Some(0x9009), 3, false), // Generic Gobi Modem device
    // 5. Gobi 2000 and 3000 devices
    QmiEntry::interface(0x413c, Some(0x8186), 0, false), // Dell Gobi 2000 Modem device (N0218, VU936)
    QmiEntry::interface(0x413c, Some(0x8194), 0, false), // Dell Gobi 3000 Composite
    QmiEntry::interface(0x05c6, Some(0x920b), 0, false), // Generic Gobi 2000 Modem device
    QmiEntry::interface(0x05c6, Some(0x9225), 0, false), // Sony Gobi 2000 Modem device (N0279, VU730)
    QmiEntry::interface(0x05c6, Some(0x9245), 0, false), // Samsung Gobi 2000 Modem device (VL176)
    QmiEntry::interface(0x03f0, Some(0x251d), 0, false), // HP Gobi 2000 Modem device (VP412)
    QmiEntry::interface(0x05c6, Some(0x9215), 0, false), // Acer Gobi 2000 Modem device (VP413)
    QmiEntry::interface(0x05c6, Some(0x9215), 4, false), // Quectel EC20 Mini PCIe
    QmiEntry::interface(0x05c6, Some(0x9265), 0, false), // Asus Gobi 2000 Modem device (VR305)
    QmiEntry::interface(0x05c6, Some(0x9235), 0, false), // Top Global Gobi 2000 Modem device (VR306)
    QmiEntry::interface(0x05c6, Some(0x9275), 0, false), // iRex Technologies Gobi 2000 Modem device (VR307)
    QmiEntry::interface(0x0af0, Some(0x8120), 0, false), // Option GTM681W
    QmiEntry::interface(0x1199, Some(0x68a5), 0, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x68a9), 0, false), // Sierra Wireless Modem
    QmiEntry::interface(0x1199, Some(0x9001), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9002), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9003), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9004), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9005), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9006), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9007), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9008), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9009), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x900a), 0, false), // Sierra Wireless Gobi 2000 Modem device (VT773)
    QmiEntry::interface(0x1199, Some(0x9011), 0, false), // Sierra Wireless Gobi 2000 Modem device (MC8305)
    QmiEntry::interface(0x16d8, Some(0x8002), 0, false), // CMDTech Gobi 2000 Modem device (VU922)
    QmiEntry::interface(0x05c6, Some(0x9205), 0, false), // Gobi 2000 Modem device
    QmiEntry::interface(0x1199, Some(0x9013), 0, false), // Sierra Wireless Gobi 3000 Modem device (MC8355)
    QmiEntry::interface(0x03f0, Some(0x371d), 0, false), // HP un2430 Mobile Broadband Module
    QmiEntry::interface(0x1199, Some(0x9015), 0, false), // Sierra Wireless Gobi 3000 Modem device
    QmiEntry::interface(0x1199, Some(0x9019), 0, false), // Sierra Wireless Gobi 3000 Modem device
    QmiEntry::interface(0x1199, Some(0x901b), 0, false), // Sierra Wireless MC7770
    QmiEntry::interface(0x12d1, Some(0x14f1), 0, false), // Sony Gobi 3000 Composite
    QmiEntry::interface(0x1410, Some(0xa021), 0, false), // Foxconn Gobi 3000 Modem device (Novatel E396)
    // Local additions, kept across regeneration
    QmiEntry::class(0x2c7c, Some(0x0127), 0xff, 0xff, 0xff, true), // Quectel EM05-CE (local entry)
];
