//! Protocol clients that open themselves on a device the bus picks.
//!
//! A client owns one USB function and speaks one management protocol. It
//! publishes the devices it can drive as [`LocalUsbClient::CLIENT_FILTER`] and
//! turns a matching device into itself with [`LocalUsbClient::open`];
//! [`UsbBusExt::request`] chains those two so a caller never spells out the
//! device request itself.

use crate::{DeviceFilter, LocalUsbBus, LocalUsbDevice};

/// A protocol client that knows how to open itself on a device.
#[trait_variant::make(UsbClient: Send)]
pub trait LocalUsbClient: Sized {
    /// Device the bus hands out, and the one [`Self::open`] takes.
    type Device: LocalUsbDevice;

    /// Failure to open, and every error the client reports afterwards.
    type Error: core::error::Error;

    /// Protocol this client speaks, for logs.
    const PROTOCOL: &'static str;

    /// Devices this client can drive, tried in order by the bus.
    const CLIENT_FILTER: &'static [DeviceFilter];

    /// Open this client on `device`.
    async fn open(device: Self::Device) -> Result<Self, Self::Error>;
}

/// Error of [`UsbBusExt::request`], which can fail on either side of the
/// handover: the bus may not find a device, or the client may not open one.
#[derive(Debug, thiserror::Error)]
pub enum RequestError<B, C> {
    /// The backend could not provide a device matching the client's filter.
    #[error("usb bus error: {0}")]
    Bus(#[source] B),
    /// The device was handed over, but the client failed to open it.
    #[error("client error: {0}")]
    Client(#[source] C),
}

/// Open a protocol client straight from a bus.
///
/// This is the one async trait without a `Send` variant: `trait_variant` turns
/// `async fn` into `fn -> impl Future + Send` but copies the body verbatim, so
/// a method that awaits a non-`Send` client cannot be generated by the macro.
#[allow(async_fn_in_trait)]
pub trait UsbBusExt: LocalUsbBus {
    /// Request the device [`LocalUsbClient`] `C` wants and open `C` on it.
    ///
    /// This is the two steps a client's `CLIENT_FILTER` exists for: ask for a
    /// device with that filter, then open the client on what came back.
    async fn request<C>(&mut self) -> Result<C, RequestError<Self::Error, C::Error>>
    where
        C: LocalUsbClient<Device = Self::Device>,
    {
        let device = self
            .request_device(C::CLIENT_FILTER)
            .await
            .map_err(RequestError::Bus)?;

        C::open(device).await.map_err(RequestError::Client)
    }
}

impl<B: LocalUsbBus> UsbBusExt for B {}
