//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-atr.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 237;
pub mod messages {
    #[doc = "Send"]
    pub mod send {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 0;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub message: String,
        }
        impl Request {
            pub const TLV_MESSAGE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_string(&self.message, 2, None)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message = reader.read_string(2, 1024)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 0;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
}
pub mod indications {
    #[doc = "Received"]
    pub mod received {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 1;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
}
