//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Types the database repeats in almost every message.

#![allow(unused_imports)]

use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
use alloc::string::String;
use alloc::vec::Vec;

#[derive(Debug, Clone, PartialEq, Default, Copy, Eq)]
pub struct OperationResult {
    pub error_status: u16,
    pub error_code: u16,
}
impl OperationResult {
    pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
        writer.write_u16(*&self.error_status, Endian::Little);
        writer.write_u16(*&self.error_code, Endian::Little);
        Ok(())
    }
    pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
        let mut out = Self::default();
        out.error_status = reader.read_u16(Endian::Little)?;
        out.error_code = reader.read_u16(Endian::Little)?;
        Ok(out)
    }
}
