//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-ims.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 18;
pub mod messages {
    #[doc = "Set IMS Policy Manager Settings"]
    pub mod set_ims_policy_manager_settings {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 71;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub acs_priority: Option<u8>,
            pub isim_priority: Option<u8>,
            pub nv_priority: Option<u8>,
            pub pco_priority: Option<u8>,
            pub service_mask: Option<u64>,
            pub apns: Option<Vec<String>>,
        }
        impl Request {
            pub const TLV_ACS_PRIORITY: u8 = 20;
            pub const TLV_ISIM_PRIORITY: u8 = 21;
            pub const TLV_NV_PRIORITY: u8 = 22;
            pub const TLV_PCO_PRIORITY: u8 = 23;
            pub const TLV_SERVICE_MASK: u8 = 24;
            pub const TLV_APNS: u8 = 25;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.acs_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.isim_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.nv_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.pco_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(23));
                }
                if let Some(value) = &self.service_mask {
                    let mut writer = TlvWriter::new();
                    writer.write_u64(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.apns {
                    let mut writer = TlvWriter::new();
                    if (value).len() != 6 {
                        return Err(Error::InvalidLength);
                    }
                    for item in value {
                        writer.write_string(item, 1, None)?;
                    }
                    tlvs.push(writer.into_tlv(25));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.acs_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.isim_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.nv_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.pco_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u64(Endian::Little)?;
                    out.service_mask = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = 6;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_string(1, 0)?);
                    }
                    let value = items;
                    out.apns = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub ims_settings_error: Option<u32>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_IMS_SETTINGS_ERROR: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_settings_error {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_settings_error = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 71;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get IMS Policy Manager Settings"]
    pub mod get_ims_policy_manager_settings {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 72;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub ims_settings_error: Option<u32>,
            pub acs_priority: Option<u8>,
            pub isim_priority: Option<u8>,
            pub nv_priority: Option<u8>,
            pub pco_priority: Option<u8>,
            pub service_mask: Option<u64>,
            pub apns: Option<Vec<String>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_IMS_SETTINGS_ERROR: u8 = 16;
            pub const TLV_ACS_PRIORITY: u8 = 21;
            pub const TLV_ISIM_PRIORITY: u8 = 22;
            pub const TLV_NV_PRIORITY: u8 = 23;
            pub const TLV_PCO_PRIORITY: u8 = 24;
            pub const TLV_SERVICE_MASK: u8 = 25;
            pub const TLV_APNS: u8 = 26;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_settings_error {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.acs_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.isim_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.nv_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(23));
                }
                if let Some(value) = &self.pco_priority {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.service_mask {
                    let mut writer = TlvWriter::new();
                    writer.write_u64(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(25));
                }
                if let Some(value) = &self.apns {
                    let mut writer = TlvWriter::new();
                    if (value).len() != 6 {
                        return Err(Error::InvalidLength);
                    }
                    for item in value {
                        writer.write_string(item, 1, None)?;
                    }
                    tlvs.push(writer.into_tlv(26));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_settings_error = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.acs_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.isim_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.nv_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.pco_priority = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u64(Endian::Little)?;
                    out.service_mask = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 26) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = 6;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_string(1, 0)?);
                    }
                    let value = items;
                    out.apns = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 72;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Set IMS Services Enabled Setting"]
    pub mod set_ims_services_enabled_setting {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 143;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub ims_voice_over_lte_enable: Option<bool>,
            pub ims_video_telephony_service_enable: Option<bool>,
            pub ims_voice_wifi_service_enable: Option<bool>,
            pub ims_call_mode_preference: Option<u32>,
            pub ims_service_enabled: Option<bool>,
            pub ims_ut_service_enable: Option<bool>,
            pub ims_sms_service_enable: Option<bool>,
            pub ims_ussd_service_enabled: Option<bool>,
            pub ims_presence_enabled: Option<bool>,
            pub ims_autoconfig_enabled: Option<bool>,
            pub ims_xdm_client_enabled: Option<bool>,
            pub ims_rcs_enabled: Option<bool>,
            pub ims_carrier_config: Option<bool>,
        }
        impl Request {
            pub const TLV_IMS_VOICE_OVER_LTE_ENABLE: u8 = 16;
            pub const TLV_IMS_VIDEO_TELEPHONY_SERVICE_ENABLE: u8 = 17;
            pub const TLV_IMS_VOICE_WIFI_SERVICE_ENABLE: u8 = 20;
            pub const TLV_IMS_CALL_MODE_PREFERENCE: u8 = 21;
            pub const TLV_IMS_SERVICE_ENABLED: u8 = 24;
            pub const TLV_IMS_UT_SERVICE_ENABLE: u8 = 25;
            pub const TLV_IMS_SMS_SERVICE_ENABLE: u8 = 26;
            pub const TLV_IMS_USSD_SERVICE_ENABLED: u8 = 28;
            pub const TLV_IMS_PRESENCE_ENABLED: u8 = 30;
            pub const TLV_IMS_AUTOCONFIG_ENABLED: u8 = 31;
            pub const TLV_IMS_XDM_CLIENT_ENABLED: u8 = 32;
            pub const TLV_IMS_RCS_ENABLED: u8 = 33;
            pub const TLV_IMS_CARRIER_CONFIG: u8 = 37;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_voice_over_lte_enable {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.ims_video_telephony_service_enable {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.ims_voice_wifi_service_enable {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.ims_call_mode_preference {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.ims_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.ims_ut_service_enable {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(25));
                }
                if let Some(value) = &self.ims_sms_service_enable {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(26));
                }
                if let Some(value) = &self.ims_ussd_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(28));
                }
                if let Some(value) = &self.ims_presence_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(30));
                }
                if let Some(value) = &self.ims_autoconfig_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(31));
                }
                if let Some(value) = &self.ims_xdm_client_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(32));
                }
                if let Some(value) = &self.ims_rcs_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(33));
                }
                if let Some(value) = &self.ims_carrier_config {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(37));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_voice_over_lte_enable = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_video_telephony_service_enable = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_voice_wifi_service_enable = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_call_mode_preference = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_ut_service_enable = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 26) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_sms_service_enable = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 28) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_ussd_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 30) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_presence_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 31) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_autoconfig_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 32) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_xdm_client_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 33) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_rcs_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 37) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_carrier_config = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 143;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get IMS Services Enabled Setting"]
    pub mod get_ims_services_enabled_setting {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 144;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub ims_voice_service_enabled: Option<bool>,
            pub ims_video_telephony_service_enabled: Option<bool>,
            pub ims_voice_wifi_service_enabled: Option<bool>,
            pub ims_registration_service_enabled: Option<bool>,
            pub ims_ut_service_enabled: Option<bool>,
            pub ims_sms_service_enabled: Option<bool>,
            pub ims_ussd_service_enabled: Option<bool>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_IMS_VOICE_SERVICE_ENABLED: u8 = 17;
            pub const TLV_IMS_VIDEO_TELEPHONY_SERVICE_ENABLED: u8 = 18;
            pub const TLV_IMS_VOICE_WIFI_SERVICE_ENABLED: u8 = 21;
            pub const TLV_IMS_REGISTRATION_SERVICE_ENABLED: u8 = 25;
            pub const TLV_IMS_UT_SERVICE_ENABLED: u8 = 26;
            pub const TLV_IMS_SMS_SERVICE_ENABLED: u8 = 27;
            pub const TLV_IMS_USSD_SERVICE_ENABLED: u8 = 29;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_voice_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.ims_video_telephony_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.ims_voice_wifi_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.ims_registration_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(25));
                }
                if let Some(value) = &self.ims_ut_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(26));
                }
                if let Some(value) = &self.ims_sms_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(27));
                }
                if let Some(value) = &self.ims_ussd_service_enabled {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(29));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_voice_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_video_telephony_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_voice_wifi_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_registration_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 26) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_ut_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 27) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_sms_service_enabled = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 29) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_ussd_service_enabled = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 144;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Bind"]
    pub mod bind {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 152;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub binding: u32,
        }
        impl Request {
            pub const TLV_BINDING: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*&self.binding, Endian::Little);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.binding = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 152;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
}
pub mod indications {
    #[doc = "IMS Policy Manager Settings Ind"]
    pub mod ims_policy_manager_settings_ind {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 73;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
    #[doc = "IMS Services Enabled Setting"]
    pub mod ims_services_enabled_setting {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 145;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
}
