//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-imsa.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 33;
pub mod messages {
    #[doc = "Get IMS Registration Status"]
    pub mod get_ims_registration_status {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 32;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub ims_registration_status: Option<u32>,
            pub ims_registration_error_code: Option<u16>,
            pub ims_registration_error_message: Option<String>,
            pub ims_registration_technology: Option<u32>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_IMS_REGISTRATION_STATUS: u8 = 18;
            pub const TLV_IMS_REGISTRATION_ERROR_CODE: u8 = 17;
            pub const TLV_IMS_REGISTRATION_ERROR_MESSAGE: u8 = 19;
            pub const TLV_IMS_REGISTRATION_TECHNOLOGY: u8 = 20;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_registration_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.ims_registration_error_code {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.ims_registration_error_message {
                    let mut writer = TlvWriter::new();
                    writer.write_string(value, 0, None)?;
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.ims_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(20));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_registration_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u16(Endian::Little)?;
                    out.ims_registration_error_code = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_string(0, 0)?;
                    out.ims_registration_error_message = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_registration_technology = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 32;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get IMS Services Status"]
    pub mod get_ims_services_status {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 33;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub ims_sms_service_status: Option<u32>,
            pub ims_voice_service_status: Option<u32>,
            pub ims_video_telephony_service_status: Option<u32>,
            pub ims_sms_service_registration_technology: Option<u32>,
            pub ims_voice_service_registration_technology: Option<u32>,
            pub ims_video_telephony_service_registration_technology: Option<u32>,
            pub ims_ue_to_tas_service_status: Option<u32>,
            pub ims_ue_to_tas_service_registration_technology: Option<u32>,
            pub ims_video_share_service_status: Option<u32>,
            pub ims_video_share_service_registration_technology: Option<u32>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_IMS_SMS_SERVICE_STATUS: u8 = 16;
            pub const TLV_IMS_VOICE_SERVICE_STATUS: u8 = 17;
            pub const TLV_IMS_VIDEO_TELEPHONY_SERVICE_STATUS: u8 = 18;
            pub const TLV_IMS_SMS_SERVICE_REGISTRATION_TECHNOLOGY: u8 = 19;
            pub const TLV_IMS_VOICE_SERVICE_REGISTRATION_TECHNOLOGY: u8 = 20;
            pub const TLV_IMS_VIDEO_TELEPHONY_SERVICE_REGISTRATION_TECHNOLOGY: u8 = 21;
            pub const TLV_IMS_UE_TO_TAS_SERVICE_STATUS: u8 = 22;
            pub const TLV_IMS_UE_TO_TAS_SERVICE_REGISTRATION_TECHNOLOGY: u8 = 23;
            pub const TLV_IMS_VIDEO_SHARE_SERVICE_STATUS: u8 = 24;
            pub const TLV_IMS_VIDEO_SHARE_SERVICE_REGISTRATION_TECHNOLOGY: u8 = 25;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_sms_service_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.ims_voice_service_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.ims_video_telephony_service_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.ims_sms_service_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.ims_voice_service_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.ims_video_telephony_service_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.ims_ue_to_tas_service_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.ims_ue_to_tas_service_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(23));
                }
                if let Some(value) = &self.ims_video_share_service_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.ims_video_share_service_registration_technology {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(25));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_sms_service_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_voice_service_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_video_telephony_service_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_sms_service_registration_technology = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_voice_service_registration_technology = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_video_telephony_service_registration_technology = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_ue_to_tas_service_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_ue_to_tas_service_registration_technology = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_video_share_service_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.ims_video_share_service_registration_technology = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 33;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Register Indications"]
    pub mod register_indications {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 34;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub ims_registration_status_changed: Option<bool>,
            pub ims_services_status_changed: Option<bool>,
        }
        impl Request {
            pub const TLV_IMS_REGISTRATION_STATUS_CHANGED: u8 = 16;
            pub const TLV_IMS_SERVICES_STATUS_CHANGED: u8 = 17;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.ims_registration_status_changed {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.ims_services_status_changed {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_registration_status_changed = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ims_services_status_changed = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 34;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Bind"]
    pub mod bind {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 51;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub binding: Option<u32>,
        }
        impl Request {
            pub const TLV_BINDING: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.binding {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.binding = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 51;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get Bind"]
    pub mod get_bind {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 52;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub binding: Option<u32>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_BINDING: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.binding {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.binding = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 52;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
}
pub mod indications {
    #[doc = "IMS Registration Status Changed"]
    pub mod ims_registration_status_changed {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 35;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
    #[doc = "IMS Services Status Changed"]
    pub mod ims_services_status_changed {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 36;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
}
