//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-pds.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 6;
pub mod messages {
    #[doc = "Reset"]
    pub mod reset {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 0;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 0;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Set Event Report"]
    pub mod set_event_report {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 1;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub nmea_position_reporting: Option<bool>,
            pub extended_nmea_position_reporting: Option<bool>,
            pub parsed_position_reporting: Option<bool>,
            pub external_xtra_data_request_reporting: Option<bool>,
            pub external_time_injection_request_reporting: Option<bool>,
            pub external_wifi_position_request_reporting: Option<bool>,
            pub satellite_information_reporting: Option<bool>,
            pub vx_network_initiated_request_reporting: Option<bool>,
            pub supl_network_initiated_prompt_reporting: Option<bool>,
            pub umts_cp_network_initiated_prompt_reporting: Option<bool>,
            pub pds_comm_event_reporting: Option<bool>,
            pub accelerometer_data_streaming_ready_reporting: Option<bool>,
            pub gyro_data_streaming_ready_reporting: Option<bool>,
            pub time_sync_request_reporting: Option<bool>,
            pub position_reliability_indicator_reporting: Option<bool>,
            pub sensor_data_usage_indicator_reporting: Option<bool>,
            pub time_source_information_reporting: Option<bool>,
            pub heading_uncertainty_reporting: Option<bool>,
            pub nmea_debug_strings_reporting: Option<bool>,
            pub extended_external_xtra_data_request_reporting: Option<bool>,
        }
        impl Request {
            pub const TLV_NMEA_POSITION_REPORTING: u8 = 16;
            pub const TLV_EXTENDED_NMEA_POSITION_REPORTING: u8 = 17;
            pub const TLV_PARSED_POSITION_REPORTING: u8 = 18;
            pub const TLV_EXTERNAL_XTRA_DATA_REQUEST_REPORTING: u8 = 19;
            pub const TLV_EXTERNAL_TIME_INJECTION_REQUEST_REPORTING: u8 = 20;
            pub const TLV_EXTERNAL_WIFI_POSITION_REQUEST_REPORTING: u8 = 21;
            pub const TLV_SATELLITE_INFORMATION_REPORTING: u8 = 22;
            pub const TLV_VX_NETWORK_INITIATED_REQUEST_REPORTING: u8 = 23;
            pub const TLV_SUPL_NETWORK_INITIATED_PROMPT_REPORTING: u8 = 24;
            pub const TLV_UMTS_CP_NETWORK_INITIATED_PROMPT_REPORTING: u8 = 25;
            pub const TLV_PDS_COMM_EVENT_REPORTING: u8 = 26;
            pub const TLV_ACCELEROMETER_DATA_STREAMING_READY_REPORTING: u8 = 27;
            pub const TLV_GYRO_DATA_STREAMING_READY_REPORTING: u8 = 28;
            pub const TLV_TIME_SYNC_REQUEST_REPORTING: u8 = 29;
            pub const TLV_POSITION_RELIABILITY_INDICATOR_REPORTING: u8 = 30;
            pub const TLV_SENSOR_DATA_USAGE_INDICATOR_REPORTING: u8 = 31;
            pub const TLV_TIME_SOURCE_INFORMATION_REPORTING: u8 = 32;
            pub const TLV_HEADING_UNCERTAINTY_REPORTING: u8 = 33;
            pub const TLV_NMEA_DEBUG_STRINGS_REPORTING: u8 = 34;
            pub const TLV_EXTENDED_EXTERNAL_XTRA_DATA_REQUEST_REPORTING: u8 = 35;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.nmea_position_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.extended_nmea_position_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.parsed_position_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.external_xtra_data_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.external_time_injection_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.external_wifi_position_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.satellite_information_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.vx_network_initiated_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(23));
                }
                if let Some(value) = &self.supl_network_initiated_prompt_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.umts_cp_network_initiated_prompt_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(25));
                }
                if let Some(value) = &self.pds_comm_event_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(26));
                }
                if let Some(value) = &self.accelerometer_data_streaming_ready_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(27));
                }
                if let Some(value) = &self.gyro_data_streaming_ready_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(28));
                }
                if let Some(value) = &self.time_sync_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(29));
                }
                if let Some(value) = &self.position_reliability_indicator_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(30));
                }
                if let Some(value) = &self.sensor_data_usage_indicator_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(31));
                }
                if let Some(value) = &self.time_source_information_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(32));
                }
                if let Some(value) = &self.heading_uncertainty_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(33));
                }
                if let Some(value) = &self.nmea_debug_strings_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(34));
                }
                if let Some(value) = &self.extended_external_xtra_data_request_reporting {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(35));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.nmea_position_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.extended_nmea_position_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.parsed_position_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.external_xtra_data_request_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.external_time_injection_request_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.external_wifi_position_request_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.satellite_information_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.vx_network_initiated_request_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.supl_network_initiated_prompt_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.umts_cp_network_initiated_prompt_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 26) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.pds_comm_event_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 27) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.accelerometer_data_streaming_ready_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 28) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.gyro_data_streaming_ready_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 29) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.time_sync_request_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 30) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.position_reliability_indicator_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 31) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.sensor_data_usage_indicator_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 32) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.time_source_information_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 33) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.heading_uncertainty_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 34) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.nmea_debug_strings_reporting = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 35) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.extended_external_xtra_data_request_reporting = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 1;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get GPS Service State"]
    pub mod get_gps_service_state {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 32;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub state: State,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_STATE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.state).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.state = State::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 32;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct State {
            pub gps_service_state: bool,
            pub tracking_session_state: u8,
        }
        impl State {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.gps_service_state));
                writer.write_u8(*&self.tracking_session_state);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.gps_service_state = reader.read_u8()? != 0;
                out.tracking_session_state = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Set GPS Service State"]
    pub mod set_gps_service_state {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 33;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub state: State,
        }
        impl Request {
            pub const TLV_STATE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.state).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.state = State::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 33;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct State {
            pub gps_service_state: bool,
        }
        impl State {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.gps_service_state));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.gps_service_state = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Get Default Tracking Session"]
    pub mod get_default_tracking_session {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 41;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub info: Info,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_INFO: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.info).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.info = Info::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 41;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Info {
            pub session_operation: u8,
            pub position_data_timeout: u8,
            pub interval: u32,
            pub accuracy_threshold: u32,
        }
        impl Info {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.session_operation);
                writer.write_u8(*&self.position_data_timeout);
                writer.write_u32(*&self.interval, Endian::Little);
                writer.write_u32(*&self.accuracy_threshold, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.session_operation = reader.read_u8()?;
                out.position_data_timeout = reader.read_u8()?;
                out.interval = reader.read_u32(Endian::Little)?;
                out.accuracy_threshold = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
    }
    #[doc = "Set Default Tracking Session"]
    pub mod set_default_tracking_session {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 42;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub info: Info,
        }
        impl Request {
            pub const TLV_INFO: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.info).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.info = Info::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 42;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Info {
            pub session_operation: u8,
            pub position_data_timeout: u8,
            pub interval: u32,
            pub accuracy_threshold: u32,
        }
        impl Info {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.session_operation);
                writer.write_u8(*&self.position_data_timeout);
                writer.write_u32(*&self.interval, Endian::Little);
                writer.write_u32(*&self.accuracy_threshold, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.session_operation = reader.read_u8()?;
                out.position_data_timeout = reader.read_u8()?;
                out.interval = reader.read_u32(Endian::Little)?;
                out.accuracy_threshold = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
    }
    #[doc = "Get AGPS Config"]
    pub mod get_agps_config {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 46;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub network_mode: Option<u8>,
        }
        impl Request {
            pub const TLV_NETWORK_MODE: u8 = 18;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.network_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(18));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.network_mode = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub location_server_address: Option<LocationServerAddress>,
            pub location_server_url: Option<Vec<u8>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_LOCATION_SERVER_ADDRESS: u8 = 16;
            pub const TLV_LOCATION_SERVER_URL: u8 = 17;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.location_server_address {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.location_server_url {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        writer.write_u8(*item);
                    }
                    tlvs.push(writer.into_tlv(17));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = LocationServerAddress::decode_from(&mut reader)?;
                    out.location_server_address = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_u8()?);
                    }
                    let value = items;
                    out.location_server_url = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 46;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct LocationServerAddress {
            pub ip: u32,
            pub port: u32,
        }
        impl LocationServerAddress {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u32(*&self.ip, Endian::Little);
                writer.write_u32(*&self.port, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.ip = reader.read_u32(Endian::Little)?;
                out.port = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
    }
    #[doc = "Set AGPS Config"]
    pub mod set_agps_config {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 47;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub location_server_address: Option<LocationServerAddress>,
            pub location_server_url: Option<Vec<u8>>,
            pub network_mode: Option<u8>,
        }
        impl Request {
            pub const TLV_LOCATION_SERVER_ADDRESS: u8 = 16;
            pub const TLV_LOCATION_SERVER_URL: u8 = 17;
            pub const TLV_NETWORK_MODE: u8 = 20;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.location_server_address {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.location_server_url {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        writer.write_u8(*item);
                    }
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.network_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(20));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = LocationServerAddress::decode_from(&mut reader)?;
                    out.location_server_address = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_u8()?);
                    }
                    let value = items;
                    out.location_server_url = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.network_mode = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 47;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct LocationServerAddress {
            pub ip: u32,
            pub port: u32,
        }
        impl LocationServerAddress {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u32(*&self.ip, Endian::Little);
                writer.write_u32(*&self.port, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.ip = reader.read_u32(Endian::Little)?;
                out.port = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
    }
    #[doc = "Get Auto Tracking State"]
    pub mod get_auto_tracking_state {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 48;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub state: State,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_STATE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.state).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.state = State::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 48;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct State {
            pub auto_tracking_state: bool,
        }
        impl State {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.auto_tracking_state));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.auto_tracking_state = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Set Auto Tracking State"]
    pub mod set_auto_tracking_state {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 49;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub state: State,
        }
        impl Request {
            pub const TLV_STATE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.state).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.state = State::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 49;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct State {
            pub auto_tracking_state: bool,
        }
        impl State {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.auto_tracking_state));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.auto_tracking_state = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
}
pub mod indications {
    #[doc = "Event Report"]
    pub mod event_report {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 1;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct ExtendedNmeaPosition {
            pub operation_mode: i8,
            pub nmea: String,
        }
        impl ExtendedNmeaPosition {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_i8(*&self.operation_mode);
                writer.write_string(&self.nmea, 2, None)?;
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.operation_mode = reader.read_i8()?;
                out.nmea = reader.read_string(2, 200)?;
                Ok(out)
            }
        }
    }
    #[doc = "GPS Ready"]
    pub mod gps_ready {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 96;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
}
