//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-voice.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 9;
pub mod messages {
    #[doc = "Indication Register"]
    pub mod indication_register {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 3;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub dtmf_events: Option<bool>,
            pub voice_privacy_events: Option<bool>,
            pub supplementary_service_notification_events: Option<bool>,
            pub call_notification_events: Option<bool>,
            pub handover_events: Option<bool>,
            pub speech_codec_events: Option<bool>,
            pub ussd_notification_events: Option<bool>,
            pub modification_events: Option<bool>,
            pub uus_events: Option<bool>,
            pub aoc_events: Option<bool>,
            pub conference_events: Option<bool>,
            pub extended_burst_type_international_information_events: Option<bool>,
            pub mt_page_miss_information_events: Option<bool>,
        }
        impl Request {
            pub const TLV_DTMF_EVENTS: u8 = 16;
            pub const TLV_VOICE_PRIVACY_EVENTS: u8 = 17;
            pub const TLV_SUPPLEMENTARY_SERVICE_NOTIFICATION_EVENTS: u8 = 18;
            pub const TLV_CALL_NOTIFICATION_EVENTS: u8 = 19;
            pub const TLV_HANDOVER_EVENTS: u8 = 20;
            pub const TLV_SPEECH_CODEC_EVENTS: u8 = 21;
            pub const TLV_USSD_NOTIFICATION_EVENTS: u8 = 22;
            pub const TLV_MODIFICATION_EVENTS: u8 = 24;
            pub const TLV_UUS_EVENTS: u8 = 25;
            pub const TLV_AOC_EVENTS: u8 = 26;
            pub const TLV_CONFERENCE_EVENTS: u8 = 27;
            pub const TLV_EXTENDED_BURST_TYPE_INTERNATIONAL_INFORMATION_EVENTS: u8 = 28;
            pub const TLV_MT_PAGE_MISS_INFORMATION_EVENTS: u8 = 29;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.dtmf_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.voice_privacy_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.supplementary_service_notification_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.call_notification_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.handover_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.speech_codec_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.ussd_notification_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.modification_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(24));
                }
                if let Some(value) = &self.uus_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(25));
                }
                if let Some(value) = &self.aoc_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(26));
                }
                if let Some(value) = &self.conference_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(27));
                }
                if let Some(value) = &self.extended_burst_type_international_information_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(28));
                }
                if let Some(value) = &self.mt_page_miss_information_events {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(29));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.dtmf_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.voice_privacy_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.supplementary_service_notification_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.call_notification_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.handover_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.speech_codec_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.ussd_notification_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.modification_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 25) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.uus_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 26) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.aoc_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 27) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.conference_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 28) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.extended_burst_type_international_information_events = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 29) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.mt_page_miss_information_events = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 3;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get Supported Messages"]
    pub mod get_supported_messages {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 30;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub list: Option<Vec<u8>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_LIST: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.list {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(
                        u16::try_from((value).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in value {
                        writer.write_u8(*item);
                    }
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u16(Endian::Little)? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_u8()?);
                    }
                    let value = items;
                    out.list = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 30;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Dial Call"]
    pub mod dial_call {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 32;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub calling_number: String,
        }
        impl Request {
            pub const TLV_CALLING_NUMBER: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_string(&self.calling_number, 0, None)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.calling_number = reader.read_string(0, 0)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 32;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "End Call"]
    pub mod end_call {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 33;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub call_id: u8,
        }
        impl Request {
            pub const TLV_CALL_ID: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.call_id);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.call_id = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 33;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Answer Call"]
    pub mod answer_call {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 34;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub call_id: u8,
        }
        impl Request {
            pub const TLV_CALL_ID: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.call_id);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.call_id = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 34;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get All Call Info"]
    pub mod get_all_call_info {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 47;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_information: Option<Vec<Call>>,
            pub remote_party_number: Option<Vec<Call2>>,
            pub alerting_type: Option<Vec<Call3>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_INFORMATION: u8 = 16;
            pub const TLV_REMOTE_PARTY_NUMBER: u8 = 17;
            pub const TLV_ALERTING_TYPE: u8 = 19;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_information {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.remote_party_number {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.alerting_type {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(19));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(Call::decode_from(&mut reader)?);
                    }
                    let value = items;
                    out.call_information = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(Call2::decode_from(&mut reader)?);
                    }
                    let value = items;
                    out.remote_party_number = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(Call3::decode_from(&mut reader)?);
                    }
                    let value = items;
                    out.alerting_type = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 47;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call {
            pub id: u8,
            pub state: u8,
            pub type_: u8,
            pub direction: u8,
            pub mode: u8,
            pub multipart_indicator: bool,
            pub als: u8,
        }
        impl Call {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.state);
                writer.write_u8(*&self.type_);
                writer.write_u8(*&self.direction);
                writer.write_u8(*&self.mode);
                writer.write_u8(u8::from(*&self.multipart_indicator));
                writer.write_u8(*&self.als);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.state = reader.read_u8()?;
                out.type_ = reader.read_u8()?;
                out.direction = reader.read_u8()?;
                out.mode = reader.read_u8()?;
                out.multipart_indicator = reader.read_u8()? != 0;
                out.als = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call2 {
            pub id: u8,
            pub presentation_indicator: u8,
            pub type_: String,
        }
        impl Call2 {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.presentation_indicator);
                writer.write_string(&self.type_, 1, None)?;
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.presentation_indicator = reader.read_u8()?;
                out.type_ = reader.read_string(1, 0)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call3 {
            pub id: u8,
            pub alerttype: u8,
        }
        impl Call3 {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.alerttype);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.alerttype = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Manage Calls"]
    pub mod manage_calls {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 49;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub service_type: u8,
            pub call_id: Option<u8>,
        }
        impl Request {
            pub const TLV_SERVICE_TYPE: u8 = 1;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.service_type);
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.service_type = reader.read_u8()?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 49;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Set Supplementary Service"]
    pub mod set_supplementary_service {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 51;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub supplementary_service_information: SupplementaryServiceInformation,
        }
        impl Request {
            pub const TLV_SUPPLEMENTARY_SERVICE_INFORMATION: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.supplementary_service_information).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.supplementary_service_information =
                    SupplementaryServiceInformation::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub service_status: Option<ServiceStatus>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_SERVICE_STATUS: u8 = 21;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.service_status {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(21));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = ServiceStatus::decode_from(&mut reader)?;
                    out.service_status = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 51;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct SupplementaryServiceInformation {
            pub supplementary_service_action: u8,
            pub supplementary_service_reason: u8,
        }
        impl SupplementaryServiceInformation {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.supplementary_service_action);
                writer.write_u8(*&self.supplementary_service_reason);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.supplementary_service_action = reader.read_u8()?;
                out.supplementary_service_reason = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct ServiceStatus {
            pub active: bool,
            pub provisioned: bool,
        }
        impl ServiceStatus {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.active));
                writer.write_u8(u8::from(*&self.provisioned));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.active = reader.read_u8()? != 0;
                out.provisioned = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Get Call Waiting"]
    pub mod get_call_waiting {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 52;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub service_class: Option<u8>,
        }
        impl Request {
            pub const TLV_SERVICE_CLASS: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.service_class {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.service_class = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub service_class: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_SERVICE_CLASS: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.service_class {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.service_class = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 52;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Originate USSD"]
    pub mod originate_ussd {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 58;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub uss_data: UssData,
        }
        impl Request {
            pub const TLV_USS_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.uss_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.uss_data = UssData::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub failure_cause: Option<u16>,
            pub alpha_identifier: Option<AlphaIdentifier>,
            pub uss_data: Option<UssData2>,
            pub call_control_result_type: Option<u8>,
            pub call_id: Option<u8>,
            pub call_control_supplementary_service_type: Option<u8>,
            pub uss_data_utf16: Option<Vec<u16>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_FAILURE_CAUSE: u8 = 16;
            pub const TLV_ALPHA_IDENTIFIER: u8 = 17;
            pub const TLV_USS_DATA: u8 = 18;
            pub const TLV_CALL_CONTROL_RESULT_TYPE: u8 = 19;
            pub const TLV_CALL_ID: u8 = 20;
            pub const TLV_CALL_CONTROL_SUPPLEMENTARY_SERVICE_TYPE: u8 = 21;
            pub const TLV_USS_DATA_UTF16: u8 = 22;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.failure_cause {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.alpha_identifier {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.uss_data {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.call_control_result_type {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.call_control_supplementary_service_type {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.uss_data_utf16 {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::try_from((value).len()).map_err(|_| Error::TooLong)?);
                    for item in value {
                        writer.write_u16(*item, Endian::Little);
                    }
                    tlvs.push(writer.into_tlv(22));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u16(Endian::Little)?;
                    out.failure_cause = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = AlphaIdentifier::decode_from(&mut reader)?;
                    out.alpha_identifier = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = UssData2::decode_from(&mut reader)?;
                    out.uss_data = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_control_result_type = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_control_supplementary_service_type = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u8()? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_u16(Endian::Little)?);
                    }
                    let value = items;
                    out.uss_data_utf16 = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 58;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct AlphaIdentifier {
            pub data_coding_scheme: u8,
            pub alpha: Vec<u8>,
        }
        impl AlphaIdentifier {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.alpha).len()).map_err(|_| Error::TooLong)?);
                for item in &self.alpha {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.alpha = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData2 {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData2 {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Answer USSD"]
    pub mod answer_ussd {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 59;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub uss_data: UssData,
        }
        impl Request {
            pub const TLV_USS_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.uss_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.uss_data = UssData::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 59;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Cancel USSD"]
    pub mod cancel_ussd {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 60;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 60;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get Config"]
    pub mod get_config {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 65;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub auto_answer: Option<bool>,
            pub air_timer: Option<bool>,
            pub roam_timer: Option<bool>,
            pub tty_mode: Option<bool>,
            pub preferred_voice_service_option: Option<bool>,
            pub amr_status: Option<bool>,
            pub preferred_voice_privacy: Option<bool>,
            pub nam_index: Option<bool>,
            pub voice_domain_preference: Option<bool>,
        }
        impl Request {
            pub const TLV_AUTO_ANSWER: u8 = 16;
            pub const TLV_AIR_TIMER: u8 = 17;
            pub const TLV_ROAM_TIMER: u8 = 18;
            pub const TLV_TTY_MODE: u8 = 19;
            pub const TLV_PREFERRED_VOICE_SERVICE_OPTION: u8 = 20;
            pub const TLV_AMR_STATUS: u8 = 21;
            pub const TLV_PREFERRED_VOICE_PRIVACY: u8 = 22;
            pub const TLV_NAM_INDEX: u8 = 23;
            pub const TLV_VOICE_DOMAIN_PREFERENCE: u8 = 24;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.auto_answer {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.air_timer {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.roam_timer {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.tty_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.preferred_voice_service_option {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.amr_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.preferred_voice_privacy {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.nam_index {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(23));
                }
                if let Some(value) = &self.voice_domain_preference {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(24));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.auto_answer = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.air_timer = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.roam_timer = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.tty_mode = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.preferred_voice_service_option = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.amr_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.preferred_voice_privacy = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.nam_index = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 24) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.voice_domain_preference = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub auto_answer_status: Option<bool>,
            pub air_timer_count: Option<AirTimerCount>,
            pub roam_timer_count: Option<RoamTimerCount>,
            pub current_tty_mode: Option<u8>,
            pub current_preferred_voice_so: Option<CurrentPreferredVoiceSo>,
            pub current_amr_status: Option<CurrentAmrStatus>,
            pub current_voice_privacy_preference: Option<u8>,
            pub current_voice_domain_preference: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_AUTO_ANSWER_STATUS: u8 = 16;
            pub const TLV_AIR_TIMER_COUNT: u8 = 17;
            pub const TLV_ROAM_TIMER_COUNT: u8 = 18;
            pub const TLV_CURRENT_TTY_MODE: u8 = 19;
            pub const TLV_CURRENT_PREFERRED_VOICE_SO: u8 = 20;
            pub const TLV_CURRENT_AMR_STATUS: u8 = 21;
            pub const TLV_CURRENT_VOICE_PRIVACY_PREFERENCE: u8 = 22;
            pub const TLV_CURRENT_VOICE_DOMAIN_PREFERENCE: u8 = 23;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.auto_answer_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.air_timer_count {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.roam_timer_count {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.current_tty_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.current_preferred_voice_so {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(20));
                }
                if let Some(value) = &self.current_amr_status {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(21));
                }
                if let Some(value) = &self.current_voice_privacy_preference {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(22));
                }
                if let Some(value) = &self.current_voice_domain_preference {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(23));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.auto_answer_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = AirTimerCount::decode_from(&mut reader)?;
                    out.air_timer_count = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = RoamTimerCount::decode_from(&mut reader)?;
                    out.roam_timer_count = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.current_tty_mode = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = CurrentPreferredVoiceSo::decode_from(&mut reader)?;
                    out.current_preferred_voice_so = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 21) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = CurrentAmrStatus::decode_from(&mut reader)?;
                    out.current_amr_status = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 22) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.current_voice_privacy_preference = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 23) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.current_voice_domain_preference = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 65;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct AirTimerCount {
            pub nam_id: u8,
            pub air_timer: u32,
        }
        impl AirTimerCount {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.nam_id);
                writer.write_u32(*&self.air_timer, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.nam_id = reader.read_u8()?;
                out.air_timer = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct RoamTimerCount {
            pub nam_id: u8,
            pub roam_timer: u32,
        }
        impl RoamTimerCount {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.nam_id);
                writer.write_u32(*&self.roam_timer, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.nam_id = reader.read_u8()?;
                out.roam_timer = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct CurrentPreferredVoiceSo {
            pub nam_id: u8,
            pub evrc_capability: bool,
            pub home_page_voice_service_option: u16,
            pub home_origination_voice_service_option: u16,
            pub roaming_origination_voice_service_option: u16,
        }
        impl CurrentPreferredVoiceSo {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.nam_id);
                writer.write_u8(u8::from(*&self.evrc_capability));
                writer.write_u16(*&self.home_page_voice_service_option, Endian::Little);
                writer.write_u16(*&self.home_origination_voice_service_option, Endian::Little);
                writer.write_u16(
                    *&self.roaming_origination_voice_service_option,
                    Endian::Little,
                );
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.nam_id = reader.read_u8()?;
                out.evrc_capability = reader.read_u8()? != 0;
                out.home_page_voice_service_option = reader.read_u16(Endian::Little)?;
                out.home_origination_voice_service_option = reader.read_u16(Endian::Little)?;
                out.roaming_origination_voice_service_option = reader.read_u16(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct CurrentAmrStatus {
            pub gsm: bool,
            pub wcdma: u8,
        }
        impl CurrentAmrStatus {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.gsm));
                writer.write_u8(*&self.wcdma);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.gsm = reader.read_u8()? != 0;
                out.wcdma = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Originate USSD No Wait"]
    pub mod originate_ussd_no_wait {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 67;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub uss_data: UssData,
        }
        impl Request {
            pub const TLV_USS_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.uss_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.uss_data = UssData::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 67;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Burst DTMF"]
    pub mod burst_dtmf {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 40;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub data: Data,
        }
        impl Request {
            pub const TLV_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.data = Data::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 40;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Data {
            pub call_id: u8,
            pub digit_buffer: String,
        }
        impl Data {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.call_id);
                writer.write_string(&self.digit_buffer, 1, None)?;
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.call_id = reader.read_u8()?;
                out.digit_buffer = reader.read_string(1, 0)?;
                Ok(out)
            }
        }
    }
    #[doc = "Start Continuous DTMF"]
    pub mod start_continuous_dtmf {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 41;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub data: Data,
        }
        impl Request {
            pub const TLV_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.data = Data::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 41;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Data {
            pub call_id: u8,
            pub digit: u8,
        }
        impl Data {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.call_id);
                writer.write_u8(*&self.digit);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.call_id = reader.read_u8()?;
                out.digit = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Stop Continuous DTMF"]
    pub mod stop_continuous_dtmf {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 42;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub data: Data,
        }
        impl Request {
            pub const TLV_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.data = Data::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub call_id: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CALL_ID: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.call_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.call_id = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 42;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Data {
            pub call_id: u8,
        }
        impl Data {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.call_id);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.call_id = reader.read_u8()?;
                Ok(out)
            }
        }
    }
}
pub mod indications {
    #[doc = "All Call Status"]
    pub mod all_call_status {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 46;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call {
            pub id: u8,
            pub state: u8,
            pub type_: u8,
            pub direction: u8,
            pub mode: u8,
            pub multipart_indicator: bool,
            pub als: u8,
        }
        impl Call {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.state);
                writer.write_u8(*&self.type_);
                writer.write_u8(*&self.direction);
                writer.write_u8(*&self.mode);
                writer.write_u8(u8::from(*&self.multipart_indicator));
                writer.write_u8(*&self.als);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.state = reader.read_u8()?;
                out.type_ = reader.read_u8()?;
                out.direction = reader.read_u8()?;
                out.mode = reader.read_u8()?;
                out.multipart_indicator = reader.read_u8()? != 0;
                out.als = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call2 {
            pub id: u8,
            pub presentation_indicator: u8,
            pub type_: String,
        }
        impl Call2 {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.presentation_indicator);
                writer.write_string(&self.type_, 1, None)?;
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.presentation_indicator = reader.read_u8()?;
                out.type_ = reader.read_string(1, 0)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Call3 {
            pub id: u8,
            pub alerttype: u8,
        }
        impl Call3 {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.id);
                writer.write_u8(*&self.alerttype);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.id = reader.read_u8()?;
                out.alerttype = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Supplementary Service"]
    pub mod supplementary_service {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 50;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Info {
            pub call_id: u8,
            pub notification_type: u8,
        }
        impl Info {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.call_id);
                writer.write_u8(*&self.notification_type);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.call_id = reader.read_u8()?;
                out.notification_type = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Release USSD"]
    pub mod release_ussd {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 61;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
    #[doc = "USSD"]
    pub mod ussd {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 62;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Originate USSD No Wait"]
    pub mod originate_ussd_no_wait {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 67;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct UssData {
            pub data_coding_scheme: u8,
            pub data: Vec<u8>,
        }
        impl UssData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.data).len()).map_err(|_| Error::TooLong)?);
                for item in &self.data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.data = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct AlphaIdentifier {
            pub data_coding_scheme: u8,
            pub alpha: Vec<u8>,
        }
        impl AlphaIdentifier {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.data_coding_scheme);
                writer.write_u8(u8::try_from((&self.alpha).len()).map_err(|_| Error::TooLong)?);
                for item in &self.alpha {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.data_coding_scheme = reader.read_u8()?;
                let count = reader.read_u8()? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.alpha = items;
                Ok(out)
            }
        }
    }
}
