//! Generated by `cargo xtask qmi-codegen`; do not edit.
//!
//! Source: `qmi-service-wms.json`.

#![allow(unused_imports)]
pub const SERVICE_ID: u16 = 5;
pub mod messages {
    #[doc = "Reset"]
    pub mod reset {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 0;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 0;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Set Event Report"]
    pub mod set_event_report {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 1;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub new_mt_message_indicator: Option<NewMtMessageIndicator>,
        }
        impl Request {
            pub const TLV_NEW_MT_MESSAGE_INDICATOR: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.new_mt_message_indicator {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = NewMtMessageIndicator::decode_from(&mut reader)?;
                    out.new_mt_message_indicator = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 1;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct NewMtMessageIndicator {
            pub report: bool,
        }
        impl NewMtMessageIndicator {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.report));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.report = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Get Supported Messages"]
    pub mod get_supported_messages {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 30;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub list: Option<Vec<u8>>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_LIST: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.list {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(
                        u16::try_from((value).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in value {
                        writer.write_u8(*item);
                    }
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u16(Endian::Little)? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(reader.read_u8()?);
                    }
                    let value = items;
                    out.list = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 30;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Raw Send"]
    pub mod raw_send {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 32;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub raw_message_data: RawMessageData,
            pub cdma_force_on_dc: Option<CdmaForceOnDc>,
            pub cdma_follow_on_dc: Option<CdmaFollowOnDc>,
            pub gsm_wcdma_link_timer: Option<u8>,
            pub sms_on_ims: Option<bool>,
        }
        impl Request {
            pub const TLV_RAW_MESSAGE_DATA: u8 = 1;
            pub const TLV_CDMA_FORCE_ON_DC: u8 = 16;
            pub const TLV_CDMA_FOLLOW_ON_DC: u8 = 17;
            pub const TLV_GSM_WCDMA_LINK_TIMER: u8 = 18;
            pub const TLV_SMS_ON_IMS: u8 = 19;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.raw_message_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.cdma_force_on_dc {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.cdma_follow_on_dc {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.gsm_wcdma_link_timer {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.sms_on_ims {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(19));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.raw_message_data = RawMessageData::decode_from(&mut reader)?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = CdmaForceOnDc::decode_from(&mut reader)?;
                    out.cdma_force_on_dc = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = CdmaFollowOnDc::decode_from(&mut reader)?;
                    out.cdma_follow_on_dc = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.gsm_wcdma_link_timer = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.sms_on_ims = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub message_id: u16,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_MESSAGE_ID: u8 = 1;
            pub const TLV_CDMA_CAUSE_CODE: u8 = 16;
            pub const TLV_CDMA_ERROR_CLASS: u8 = 17;
            pub const TLV_GSM_WCDMA_CAUSE_INFO: u8 = 18;
            pub const TLV_MESSAGE_DELIVERY_FAILURE_TYPE: u8 = 19;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*&self.message_id, Endian::Little);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_id = reader.read_u16(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct ResponseError {
            pub result: crate::types::common::OperationResult,
            pub cdma_cause_code: Option<u16>,
            pub cdma_error_class: Option<u8>,
            pub gsm_wcdma_cause_info: Option<GsmWcdmaCauseInfo>,
            pub message_delivery_failure_type: Option<u8>,
        }
        impl ResponseError {
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let result = crate::result::decode_result(tlvs)?;
                let mut out = Self {
                    result,
                    ..Default::default()
                };
                {
                    let out = &mut out;
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u16(Endian::Little)?;
                            out.cdma_cause_code = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u8()?;
                            out.cdma_error_class = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = GsmWcdmaCauseInfo::decode_from(&mut reader)?;
                            out.gsm_wcdma_cause_info = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u8()?;
                            out.message_delivery_failure_type = Some(value);
                        }
                    }
                }
                Ok(out)
            }
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut result = TlvWriter::new();
                self.result.encode_to(&mut result)?;
                let mut tlvs = alloc::vec![result.into_tlv(crate::TLV_RESULT)];
                if let Some(value) = &self.cdma_cause_code {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.cdma_error_class {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.gsm_wcdma_cause_info {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.message_delivery_failure_type {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(19));
                }
                Ok(tlvs)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 32;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct RawMessageData {
            pub format: u8,
            pub raw_data: Vec<u8>,
        }
        impl RawMessageData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.format);
                writer.write_u16(
                    u16::try_from((&self.raw_data).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.raw_data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.format = reader.read_u8()?;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.raw_data = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct CdmaForceOnDc {
            pub force: bool,
            pub service_option: u8,
        }
        impl CdmaForceOnDc {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.force));
                writer.write_u8(*&self.service_option);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.force = reader.read_u8()? != 0;
                out.service_option = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct CdmaFollowOnDc {
            pub follow: bool,
        }
        impl CdmaFollowOnDc {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.follow));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.follow = reader.read_u8()? != 0;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct GsmWcdmaCauseInfo {
            pub rp_cause: u16,
            pub tp_cause: u8,
        }
        impl GsmWcdmaCauseInfo {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u16(*&self.rp_cause, Endian::Little);
                writer.write_u8(*&self.tp_cause);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.rp_cause = reader.read_u16(Endian::Little)?;
                out.tp_cause = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Raw Write"]
    pub mod raw_write {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 33;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub raw_message_data: RawMessageData,
        }
        impl Request {
            pub const TLV_RAW_MESSAGE_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.raw_message_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.raw_message_data = RawMessageData::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub memory_index: u32,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_MEMORY_INDEX: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*&self.memory_index, Endian::Little);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.memory_index = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 33;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct RawMessageData {
            pub storage_type: u8,
            pub format: u8,
            pub raw_data: Vec<u8>,
        }
        impl RawMessageData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.storage_type);
                writer.write_u8(*&self.format);
                writer.write_u16(
                    u16::try_from((&self.raw_data).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.raw_data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.storage_type = reader.read_u8()?;
                out.format = reader.read_u8()?;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.raw_data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Raw Read"]
    pub mod raw_read {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 34;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub message_memory_storage_id: MessageMemoryStorageId,
            pub message_mode: Option<u8>,
            pub sms_on_ims: Option<bool>,
        }
        impl Request {
            pub const TLV_MESSAGE_MEMORY_STORAGE_ID: u8 = 1;
            pub const TLV_MESSAGE_MODE: u8 = 16;
            pub const TLV_SMS_ON_IMS: u8 = 17;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.message_memory_storage_id).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.message_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.sms_on_ims {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_memory_storage_id = MessageMemoryStorageId::decode_from(&mut reader)?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_mode = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.sms_on_ims = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub raw_message_data: RawMessageData,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_RAW_MESSAGE_DATA: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.raw_message_data).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.raw_message_data = RawMessageData::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 34;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct MessageMemoryStorageId {
            pub storage_type: u8,
            pub memory_index: u32,
        }
        impl MessageMemoryStorageId {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.storage_type);
                writer.write_u32(*&self.memory_index, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.storage_type = reader.read_u8()?;
                out.memory_index = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct RawMessageData {
            pub message_tag: u8,
            pub format: u8,
            pub raw_data: Vec<u8>,
        }
        impl RawMessageData {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.message_tag);
                writer.write_u8(*&self.format);
                writer.write_u16(
                    u16::try_from((&self.raw_data).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.raw_data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.message_tag = reader.read_u8()?;
                out.format = reader.read_u8()?;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.raw_data = items;
                Ok(out)
            }
        }
    }
    #[doc = "Modify Tag"]
    pub mod modify_tag {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 35;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub message_tag: MessageTag,
            pub message_mode: Option<u8>,
        }
        impl Request {
            pub const TLV_MESSAGE_TAG: u8 = 1;
            pub const TLV_MESSAGE_MODE: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.message_tag).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.message_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_tag = MessageTag::decode_from(&mut reader)?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_mode = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 35;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct MessageTag {
            pub storage_type: u8,
            pub memory_index: u32,
            pub message_tag: u8,
        }
        impl MessageTag {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.storage_type);
                writer.write_u32(*&self.memory_index, Endian::Little);
                writer.write_u8(*&self.message_tag);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.storage_type = reader.read_u8()?;
                out.memory_index = reader.read_u32(Endian::Little)?;
                out.message_tag = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Delete"]
    pub mod delete {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 36;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub memory_storage: u8,
            pub memory_index: Option<u32>,
            pub message_tag: Option<u8>,
            pub message_mode: Option<u8>,
        }
        impl Request {
            pub const TLV_MEMORY_STORAGE: u8 = 1;
            pub const TLV_MEMORY_INDEX: u8 = 16;
            pub const TLV_MESSAGE_TAG: u8 = 17;
            pub const TLV_MESSAGE_MODE: u8 = 18;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.memory_storage);
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.memory_index {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.message_tag {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.message_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(18));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.memory_storage = reader.read_u8()?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u32(Endian::Little)?;
                    out.memory_index = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_tag = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_mode = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 36;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get Message Protocol"]
    pub mod get_message_protocol {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 48;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub message_protocol: u8,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_MESSAGE_PROTOCOL: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.message_protocol);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_protocol = reader.read_u8()?;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 48;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "List Messages"]
    pub mod list_messages {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 49;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub storage_type: u8,
            pub message_tag: Option<u8>,
            pub message_mode: Option<u8>,
        }
        impl Request {
            pub const TLV_STORAGE_TYPE: u8 = 1;
            pub const TLV_MESSAGE_TAG: u8 = 17;
            pub const TLV_MESSAGE_MODE: u8 = 18;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.storage_type);
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.message_tag {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.message_mode {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(18));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.storage_type = reader.read_u8()?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_tag = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.message_mode = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub message_list: Vec<Element>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_MESSAGE_LIST: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u32(
                        u32::try_from((&self.message_list).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in &self.message_list {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                let count = reader.read_u32(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(Element::decode_from(&mut reader)?);
                }
                out.message_list = items;
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 49;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Element {
            pub memory_index: u32,
            pub message_tag: u8,
        }
        impl Element {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u32(*&self.memory_index, Endian::Little);
                writer.write_u8(*&self.message_tag);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.memory_index = reader.read_u32(Endian::Little)?;
                out.message_tag = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Set Routes"]
    pub mod set_routes {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 50;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub route_list: Vec<Element>,
            pub transfer_status_report: Option<u8>,
        }
        impl Request {
            pub const TLV_ROUTE_LIST: u8 = 1;
            pub const TLV_TRANSFER_STATUS_REPORT: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(
                        u16::try_from((&self.route_list).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in &self.route_list {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.transfer_status_report {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(Element::decode_from(&mut reader)?);
                }
                out.route_list = items;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.transfer_status_report = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 50;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Element {
            pub message_type: u8,
            pub message_class: u8,
            pub storage: u8,
            pub receipt_action: u8,
        }
        impl Element {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.message_type);
                writer.write_u8(*&self.message_class);
                writer.write_u8(*&self.storage);
                writer.write_u8(*&self.receipt_action);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.message_type = reader.read_u8()?;
                out.message_class = reader.read_u8()?;
                out.storage = reader.read_u8()?;
                out.receipt_action = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Get Routes"]
    pub mod get_routes {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 51;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub route_list: Vec<Element>,
            pub transfer_status_report: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_ROUTE_LIST: u8 = 1;
            pub const TLV_TRANSFER_STATUS_REPORT: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(
                        u16::try_from((&self.route_list).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in &self.route_list {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.transfer_status_report {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(Element::decode_from(&mut reader)?);
                }
                out.route_list = items;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.transfer_status_report = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 51;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Element {
            pub message_type: u8,
            pub message_class: u8,
            pub storage: u8,
            pub receipt_action: u8,
        }
        impl Element {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.message_type);
                writer.write_u8(*&self.message_class);
                writer.write_u8(*&self.storage);
                writer.write_u8(*&self.receipt_action);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.message_type = reader.read_u8()?;
                out.message_class = reader.read_u8()?;
                out.storage = reader.read_u8()?;
                out.receipt_action = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Send Ack"]
    pub mod send_ack {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 55;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub information: Information,
            pub n_3gpp2_failure_information: Option<N3gpp2FailureInformation>,
            pub n_3gpp_failure_information: Option<N3gppFailureInformation>,
            pub sms_on_ims: Option<bool>,
        }
        impl Request {
            pub const TLV_INFORMATION: u8 = 1;
            pub const TLV_N_3GPP2_FAILURE_INFORMATION: u8 = 16;
            pub const TLV_N_3GPP_FAILURE_INFORMATION: u8 = 17;
            pub const TLV_SMS_ON_IMS: u8 = 18;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.information).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.n_3gpp2_failure_information {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                if let Some(value) = &self.n_3gpp_failure_information {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.sms_on_ims {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(18));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.information = Information::decode_from(&mut reader)?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = N3gpp2FailureInformation::decode_from(&mut reader)?;
                    out.n_3gpp2_failure_information = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = N3gppFailureInformation::decode_from(&mut reader)?;
                    out.n_3gpp_failure_information = Some(value);
                }
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.sms_on_ims = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_FAILURE_CAUSE: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct ResponseError {
            pub result: crate::types::common::OperationResult,
            pub failure_cause: Option<u8>,
        }
        impl ResponseError {
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let result = crate::result::decode_result(tlvs)?;
                let mut out = Self {
                    result,
                    ..Default::default()
                };
                {
                    let out = &mut out;
                    if out.result.error_code == 84 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u8()?;
                            out.failure_cause = Some(value);
                        }
                    }
                }
                Ok(out)
            }
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut result = TlvWriter::new();
                self.result.encode_to(&mut result)?;
                let mut tlvs = alloc::vec![result.into_tlv(crate::TLV_RESULT)];
                if let Some(value) = &self.failure_cause {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 55;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Information {
            pub transaction_id: u32,
            pub message_protocol: u8,
            pub success: bool,
        }
        impl Information {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u32(*&self.transaction_id, Endian::Little);
                writer.write_u8(*&self.message_protocol);
                writer.write_u8(u8::from(*&self.success));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.transaction_id = reader.read_u32(Endian::Little)?;
                out.message_protocol = reader.read_u8()?;
                out.success = reader.read_u8()? != 0;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct N3gpp2FailureInformation {
            pub error_class: u8,
            pub cause_code: u8,
        }
        impl N3gpp2FailureInformation {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.error_class);
                writer.write_u8(*&self.cause_code);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.error_class = reader.read_u8()?;
                out.cause_code = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct N3gppFailureInformation {
            pub rp_cause: u8,
            pub tp_cause: u8,
        }
        impl N3gppFailureInformation {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.rp_cause);
                writer.write_u8(*&self.tp_cause);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.rp_cause = reader.read_u8()?;
                out.tp_cause = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Set Broadcast Activation"]
    pub mod set_broadcast_activation {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 60;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub activation: Activation,
        }
        impl Request {
            pub const TLV_ACTIVATION: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.activation).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.activation = Activation::decode_from(&mut reader)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 60;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Activation {
            pub message_mode: u8,
            pub activate: bool,
        }
        impl Activation {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.message_mode);
                writer.write_u8(u8::from(*&self.activate));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.message_mode = reader.read_u8()?;
                out.activate = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Set Broadcast Config"]
    pub mod set_broadcast_config {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 61;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub message_mode: u8,
            pub channels: Option<Vec<Element>>,
        }
        impl Request {
            pub const TLV_MESSAGE_MODE: u8 = 1;
            pub const TLV_CHANNELS: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.message_mode);
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.channels {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(
                        u16::try_from((value).len()).map_err(|_| Error::TooLong)?,
                        Endian::Little,
                    );
                    for item in value {
                        (item).encode_to(&mut writer)?;
                    }
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_mode = reader.read_u8()?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let count = reader.read_u16(Endian::Little)? as usize;
                    let mut items = Vec::with_capacity(count.min(256));
                    for _ in 0..count {
                        items.push(Element::decode_from(&mut reader)?);
                    }
                    let value = items;
                    out.channels = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 61;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Element {
            pub start: u16,
            pub end: u16,
            pub selected: bool,
        }
        impl Element {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u16(*&self.start, Endian::Little);
                writer.write_u16(*&self.end, Endian::Little);
                writer.write_u8(u8::from(*&self.selected));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.start = reader.read_u16(Endian::Little)?;
                out.end = reader.read_u16(Endian::Little)?;
                out.selected = reader.read_u8()? != 0;
                Ok(out)
            }
        }
    }
    #[doc = "Get Broadcast Config"]
    pub mod get_broadcast_config {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 62;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub message_mode: u8,
        }
        impl Request {
            pub const TLV_MESSAGE_MODE: u8 = 1;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*&self.message_mode);
                    tlvs.push(writer.into_tlv(1));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.message_mode = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub config: Option<Config>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_CONFIG: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.config {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = Config::decode_from(&mut reader)?;
                    out.config = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 62;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Element {
            pub start: u16,
            pub end: u16,
            pub selected: bool,
        }
        impl Element {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u16(*&self.start, Endian::Little);
                writer.write_u16(*&self.end, Endian::Little);
                writer.write_u8(u8::from(*&self.selected));
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.start = reader.read_u16(Endian::Little)?;
                out.end = reader.read_u16(Endian::Little)?;
                out.selected = reader.read_u8()? != 0;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Config {
            pub activated: bool,
            pub channels: Vec<Element>,
        }
        impl Config {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(u8::from(*&self.activated));
                writer.write_u16(
                    u16::try_from((&self.channels).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.channels {
                    (item).encode_to(writer)?;
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.activated = reader.read_u8()? != 0;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(Element::decode_from(reader)?);
                }
                out.channels = items;
                Ok(out)
            }
        }
    }
    #[doc = "Send From Memory Storage"]
    pub mod send_from_memory_storage {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 66;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub information: Information,
            pub sms_on_ims: Option<bool>,
        }
        impl Request {
            pub const TLV_INFORMATION: u8 = 1;
            pub const TLV_SMS_ON_IMS: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                {
                    let mut writer = TlvWriter::new();
                    (&self.information).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(1));
                }
                if let Some(value) = &self.sms_on_ims {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                let tlv = tlvs
                    .iter()
                    .find(|tlv| tlv.id == 1)
                    .ok_or(Error::MissingTlv { id: 1 })?;
                let mut reader = TlvReader::new(&tlv.value);
                out.information = Information::decode_from(&mut reader)?;
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.sms_on_ims = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub message_id: Option<u16>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_MESSAGE_ID: u8 = 16;
            pub const TLV_CDMA_CAUSE_CODE: u8 = 17;
            pub const TLV_CDMA_ERROR_CLASS: u8 = 18;
            pub const TLV_GSM_WCDMA_CAUSE_INFO: u8 = 19;
            pub const TLV_MESSAGE_DELIVERY_FAILURE_TYPE: u8 = 20;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.message_id {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u16(Endian::Little)?;
                    out.message_id = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct ResponseError {
            pub result: crate::types::common::OperationResult,
            pub cdma_cause_code: Option<u16>,
            pub cdma_error_class: Option<u8>,
            pub gsm_wcdma_cause_info: Option<GsmWcdmaCauseInfo>,
            pub message_delivery_failure_type: Option<u8>,
        }
        impl ResponseError {
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let result = crate::result::decode_result(tlvs)?;
                let mut out = Self {
                    result,
                    ..Default::default()
                };
                {
                    let out = &mut out;
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u16(Endian::Little)?;
                            out.cdma_cause_code = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 18) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u8()?;
                            out.cdma_error_class = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 19) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = GsmWcdmaCauseInfo::decode_from(&mut reader)?;
                            out.gsm_wcdma_cause_info = Some(value);
                        }
                    }
                    if out.result.error_code == 54 {
                        if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 20) {
                            let mut reader = TlvReader::new(&tlv.value);
                            let value = reader.read_u8()?;
                            out.message_delivery_failure_type = Some(value);
                        }
                    }
                }
                Ok(out)
            }
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut result = TlvWriter::new();
                self.result.encode_to(&mut result)?;
                let mut tlvs = alloc::vec![result.into_tlv(crate::TLV_RESULT)];
                if let Some(value) = &self.cdma_cause_code {
                    let mut writer = TlvWriter::new();
                    writer.write_u16(*value, Endian::Little);
                    tlvs.push(writer.into_tlv(17));
                }
                if let Some(value) = &self.cdma_error_class {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(18));
                }
                if let Some(value) = &self.gsm_wcdma_cause_info {
                    let mut writer = TlvWriter::new();
                    (value).encode_to(&mut writer)?;
                    tlvs.push(writer.into_tlv(19));
                }
                if let Some(value) = &self.message_delivery_failure_type {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(20));
                }
                Ok(tlvs)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 66;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Information {
            pub storage_type: u8,
            pub memory_index: u32,
            pub message_mode: u8,
        }
        impl Information {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.storage_type);
                writer.write_u32(*&self.memory_index, Endian::Little);
                writer.write_u8(*&self.message_mode);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.storage_type = reader.read_u8()?;
                out.memory_index = reader.read_u32(Endian::Little)?;
                out.message_mode = reader.read_u8()?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct GsmWcdmaCauseInfo {
            pub rp_cause: u16,
            pub tp_cause: u8,
        }
        impl GsmWcdmaCauseInfo {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u16(*&self.rp_cause, Endian::Little);
                writer.write_u8(*&self.tp_cause);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.rp_cause = reader.read_u16(Endian::Little)?;
                out.tp_cause = reader.read_u8()?;
                Ok(out)
            }
        }
    }
    #[doc = "Indication Register"]
    pub mod indication_register {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 71;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {
            pub report_transport_network_registration_status: Option<bool>,
        }
        impl Request {
            pub const TLV_REPORT_TRANSPORT_NETWORK_REGISTRATION_STATUS: u8 = 17;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.report_transport_network_registration_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(u8::from(*value));
                    tlvs.push(writer.into_tlv(17));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 17) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()? != 0;
                    out.report_transport_network_registration_status = Some(value);
                }
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {}
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 71;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
    #[doc = "Get Transport Network Registration Status"]
    pub mod get_transport_network_registration_status {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 74;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Request {}
        impl Request {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Response {
            pub registration_status: Option<u8>,
        }
        impl Response {
            pub const TLV_RESULT: u8 = 2;
            pub const TLV_REGISTRATION_STATUS: u8 = 16;
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = Vec::new();
                if let Some(value) = &self.registration_status {
                    let mut writer = TlvWriter::new();
                    writer.write_u8(*value);
                    tlvs.push(writer.into_tlv(16));
                }
                Ok(tlvs)
            }
            pub fn from_tlvs(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                let mut out = Self::default();
                if let Some(tlv) = tlvs.iter().find(|tlv| tlv.id == 16) {
                    let mut reader = TlvReader::new(&tlv.value);
                    let value = reader.read_u8()?;
                    out.registration_status = Some(value);
                }
                Ok(out)
            }
        }
        impl crate::Response for Response {
            type Request = Request;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                let mut tlvs = crate::result::success_tlvs();
                tlvs.extend(self.to_tlvs()?);
                Ok(tlvs)
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                crate::result::check_result(tlvs)?;
                Response::from_tlvs(tlvs)
            }
        }
        impl crate::Request for Request {
            const SERVICE: u16 = super::super::SERVICE_ID;
            const MESSAGE_ID: u16 = 74;
            type Response = Response;
            fn encode(&self) -> Result<Vec<TlvBuf>, Error> {
                self.to_tlvs()
            }
            fn decode(tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Self::from_tlvs(tlvs)
            }
        }
    }
}
pub mod indications {
    #[doc = "Event Report"]
    pub mod event_report {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 1;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct MtMessage {
            pub storage_type: u8,
            pub memory_index: u32,
        }
        impl MtMessage {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.storage_type);
                writer.write_u32(*&self.memory_index, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.storage_type = reader.read_u8()?;
                out.memory_index = reader.read_u32(Endian::Little)?;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct TransferRouteMtMessage {
            pub ack_indicator: u8,
            pub transaction_id: u32,
            pub format: u8,
            pub raw_data: Vec<u8>,
        }
        impl TransferRouteMtMessage {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.ack_indicator);
                writer.write_u32(*&self.transaction_id, Endian::Little);
                writer.write_u8(*&self.format);
                writer.write_u16(
                    u16::try_from((&self.raw_data).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.raw_data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.ack_indicator = reader.read_u8()?;
                out.transaction_id = reader.read_u32(Endian::Little)?;
                out.format = reader.read_u8()?;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.raw_data = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct EtwsMessage {
            pub notification_type: u8,
            pub raw_data: Vec<u8>,
        }
        impl EtwsMessage {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u8(*&self.notification_type);
                writer.write_u16(
                    u16::try_from((&self.raw_data).len()).map_err(|_| Error::TooLong)?,
                    Endian::Little,
                );
                for item in &self.raw_data {
                    writer.write_u8(*item);
                }
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.notification_type = reader.read_u8()?;
                let count = reader.read_u16(Endian::Little)? as usize;
                let mut items = Vec::with_capacity(count.min(256));
                for _ in 0..count {
                    items.push(reader.read_u8()?);
                }
                out.raw_data = items;
                Ok(out)
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct EtwsPlmnInformation {
            pub mcc: u16,
            pub mnc: u16,
        }
        impl EtwsPlmnInformation {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_u16(*&self.mcc, Endian::Little);
                writer.write_u16(*&self.mnc, Endian::Little);
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.mcc = reader.read_u16(Endian::Little)?;
                out.mnc = reader.read_u16(Endian::Little)?;
                Ok(out)
            }
        }
    }
    #[doc = "SMSC Address"]
    pub mod smsc_address {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 70;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Address {
            pub type_: String,
            pub digits: String,
        }
        impl Address {
            pub fn encode_to(&self, writer: &mut TlvWriter) -> Result<(), Error> {
                writer.write_string(&self.type_, 0, Some(3))?;
                writer.write_string(&self.digits, 1, None)?;
                Ok(())
            }
            pub fn decode_from(reader: &mut TlvReader<'_>) -> Result<Self, Error> {
                let mut out = Self::default();
                out.type_ = reader.read_fixed_string(3)?;
                out.digits = reader.read_string(1, 0)?;
                Ok(out)
            }
        }
    }
    #[doc = "Transport Network Registration Status"]
    pub mod transport_network_registration_status {
        use crate::{Endian, Error, TlvBuf, TlvReader, TlvWriter};
        use alloc::string::String;
        use alloc::vec::Vec;
        pub const MESSAGE_ID: u16 = 75;
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct Indication {}
        impl Indication {
            pub fn to_tlvs(&self) -> Result<Vec<TlvBuf>, Error> {
                Ok(Vec::new())
            }
            pub fn from_tlvs(_tlvs: &[TlvBuf]) -> Result<Self, Error> {
                Ok(Self::default())
            }
        }
    }
}
