//! Generator for the MBIM service types of `rm-mbim`.
//!
//! Each `libmbim` `mbim-service-*.json` file is expanded into the module body
//! of one `rm-mbim::types` submodule: the command builders, the `CID`
//! constants and the struct codecs.

use std::collections::HashMap;
use std::error::Error;
use std::path::Path;

use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};
use serde_json::Value;

use crate::services::{file_name, files, module_name};

/// Header of the generated files.
const BANNER: &str = "//! Generated by `cargo xtask mbim-codegen`; do not edit.";

/// File name prefix of the service database.
const PREFIX: &str = "mbim-service-";

/// Generate `types.rs` and the `types/` modules of one crate.
pub fn generate(data: &Path, output: &Path) -> Result<(), Box<dyn Error>> {
    let mut manifest = String::from(BANNER);
    manifest.push_str(&format!(
        "\n//!\n//! Source: the libmbim service database in `{}`.\n\n",
        file_name(data)
    ));
    // Types expanded from the database are not written for the lints.
    manifest.push_str("#![allow(clippy::all)]\n\n");

    for file in files(data, PREFIX)? {
        let name = module_name(&file, PREFIX);
        let header = format!("{BANNER}\n//!\n//! Source: `{}`.\n\n", file_name(&file));
        let path = output.join("types").join(format!("{name}.rs"));

        crate::rust::write(&path, crate::rust::render(&header, &module_body(&file)?))?;
        manifest.push_str(&format!("pub mod {name};\n"));
    }

    crate::rust::write(&output.join("types.rs"), manifest)
}

/// Expand one `mbim-service-*.json` database file into a module body.
fn module_body(file: &Path) -> Result<TokenStream, Box<dyn Error>> {
    let source = std::fs::read_to_string(file)
        .map_err(|error| format!("unable to read {}: {error}", file.display()))?;
    let source = strip_comments(&source);
    let entries: Vec<Value> = serde_json::from_str(&source)
        .map_err(|error| format!("invalid MBIM database {}: {error}", file.display()))?;

    Ok(expand(&entries))
}

#[derive(Clone, Debug)]
struct Field {
    ident: Ident,
    format: String,
    struct_type: Option<Ident>,
    _array_size_field: Option<Ident>,
    utf8: bool,
}

#[derive(Clone, Debug)]
struct StructDef {
    ident: Ident,
    fields: Vec<Field>,
}

#[derive(Clone, Debug)]
struct CommandDef {
    ident: Ident,
    cid: u32,
    query: Vec<Field>,
    set: Vec<Field>,
    response: Vec<Field>,
    indication: Vec<Field>,
    has_query: bool,
    has_set: bool,
    has_response: bool,
    has_indication: bool,
}

/// Expand the entries of one database file into the module body.
fn expand(entries: &[Value]) -> proc_macro2::TokenStream {
    let service_name = entries
        .iter()
        .find(|entry| entry.get("type").and_then(Value::as_str) == Some("Service"))
        .and_then(|entry| entry.get("name"))
        .and_then(Value::as_str)
        .unwrap_or("MBIM Service");
    let service_uuid = find_service_uuid(service_name);

    let mut structs = Vec::new();
    let mut commands = Vec::new();
    let mut next_cid = 1u32;
    for entry in entries {
        match entry.get("type").and_then(Value::as_str) {
            Some("Struct") => structs.push(parse_struct(entry)),
            Some("Command") => {
                commands.push(parse_command(entry, next_cid));
                next_cid += 1;
            }
            _ => {}
        }
    }

    let struct_tokens = structs.iter().map(emit_struct);
    let command_tokens = commands.iter().map(emit_command);
    let specs = commands.iter().map(|command| {
        let name = command.ident.to_string();
        let cid = command.cid;
        let query = command.has_query;
        let set = command.has_set;
        let response = command.has_response;
        quote! {
            crate::CommandSpec { name: #name, cid: #cid, query: #query, set: #set, response: #response }
        }
    });
    let cids = commands.iter().map(|command| {
        let ident = snake_ident(&command.ident.to_string());
        let ident = format_ident!("{}", ident.to_string().to_uppercase());
        let cid = command.cid;
        quote! { pub const #ident: u32 = #cid; }
    });
    let uuid = uuid_tokens(&service_uuid);
    quote! {
        // The database does not say which parts of a command are used, so the
        // builders are written for the general case.
        #![allow(unused_imports, unused_mut, unused_variables)]

        pub const SERVICE: crate::Uuid = #uuid;
        pub const SERVICE_NAME: &str = #service_name;
        pub mod cid {
            #(#cids)*
        }
        pub const COMMANDS: &[crate::CommandSpec] = &[#(#specs),*];
        #(#struct_tokens)*
        #(#command_tokens)*
    }
}

fn parse_struct(entry: &Value) -> StructDef {
    let ident = type_ident(
        entry
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or("Anonymous"),
    );
    let fields = parse_fields(entry.get("contents"));
    StructDef { ident, fields }
}

fn parse_command(entry: &Value, cid: u32) -> CommandDef {
    let ident = type_ident(
        entry
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or("Command"),
    );
    let query_value = entry.get("query");
    let set_value = entry.get("set");
    let response_value = entry.get("response");
    let indication_value = entry
        .get("notification")
        .or_else(|| entry.get("indication"));
    CommandDef {
        ident,
        cid,
        query: parse_fields(query_value),
        set: parse_fields(set_value),
        response: parse_fields(response_value),
        indication: parse_fields(indication_value),
        has_query: query_value.is_some(),
        has_set: set_value.is_some(),
        has_response: response_value.is_some(),
        has_indication: indication_value.is_some(),
    }
}

fn parse_fields(value: Option<&Value>) -> Vec<Field> {
    value
        .and_then(Value::as_array)
        .map(|fields| {
            fields
                .iter()
                .map(|field| Field {
                    ident: field_ident(
                        field.get("name").and_then(Value::as_str).unwrap_or("field"),
                    ),
                    format: field
                        .get("format")
                        .and_then(Value::as_str)
                        .unwrap_or("raw")
                        .to_owned(),
                    struct_type: field
                        .get("struct-type")
                        .and_then(Value::as_str)
                        .map(type_ident),
                    _array_size_field: field
                        .get("array-size-field")
                        .and_then(Value::as_str)
                        .map(field_ident),
                    utf8: field.get("encoding").and_then(Value::as_str) == Some("utf-8"),
                })
                .collect()
        })
        .unwrap_or_default()
}

fn emit_struct(def: &StructDef) -> proc_macro2::TokenStream {
    let name = &def.ident;
    let fields = def.fields.iter().map(|field| {
        let ident = &field.ident;
        let ty = field_type(field, false);
        quote! { pub #ident: #ty }
    });
    let encode = def.fields.iter().map(|field| encode_field(field, false));
    let decode = def
        .fields
        .iter()
        .map(|field| decode_field(field, false, false));
    quote! {
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct #name {
            #(#fields,)*
        }
        impl #name {
            pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
                #(#encode)*
            }
            pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
                Ok(Self { #(#decode,)* })
            }
        }
    }
}

/// Emit one command module: its request types, its response and indication,
/// and the [`crate::Request`] implementations binding them to the service.
fn emit_command(command: &CommandDef) -> proc_macro2::TokenStream {
    let module = snake_ident(&command.ident.to_string());
    let cid = command.cid;
    let indication_type = format_ident!("Indication");
    let indication_fields = fields_tokens(&command.indication);
    let indication_decode = command
        .indication
        .iter()
        .map(|field| decode_field(field, true, true));

    // A response answers one request, so the two kinds get their own response
    // type even though the database describes a single response.
    let query_block = command.has_query.then(|| {
        emit_exchange(
            &format_ident!("QueryRequest"),
            &format_ident!("QueryResponse"),
            &command.query,
            &command.response,
            quote! { crate::CommandType::Query },
            cid,
        )
    });
    let set_block = command.has_set.then(|| {
        emit_exchange(
            &format_ident!("SetRequest"),
            &format_ident!("SetResponse"),
            &command.set,
            &command.response,
            quote! { crate::CommandType::Set },
            cid,
        )
    });
    let indication_block = command.has_indication.then(|| {
        quote! {
            #[derive(Debug, Clone, PartialEq, Default)]
            pub struct #indication_type { #(#indication_fields,)* }
            impl #indication_type {
                pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
                    let mut decoder = crate::codec::Decoder::new(bytes);
                    Ok(Self { #(#indication_decode,)* })
                }
            }
        }
    });

    quote! {
        pub mod #module {
            pub const CID: u32 = #cid;
            #query_block
            #set_block
            #indication_block
        }
    }
}

/// Emit a request, the response it is answered with, and the [`crate::Request`]
/// and [`crate::Response`] implementations binding the two together.
fn emit_exchange(
    request_type: &Ident,
    response_type: &Ident,
    request_fields: &[Field],
    response_fields: &[Field],
    command_type: proc_macro2::TokenStream,
    cid: u32,
) -> proc_macro2::TokenStream {
    let request_members = fields_tokens(request_fields);
    let request_encode = request_fields.iter().map(|field| encode_field(field, true));
    let request_decode = request_fields
        .iter()
        .map(|field| decode_field(field, true, true));

    let response_members = fields_tokens(response_fields);
    let response_encode = response_fields
        .iter()
        .map(|field| encode_field(field, true));
    let response_decode = response_fields
        .iter()
        .map(|field| decode_field(field, true, true));

    quote! {
        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct #request_type { #(#request_members,)* }

        impl #request_type {
            pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
                let mut encoder = crate::codec::Encoder::new();
                #(#request_encode)*
                encoder.finish()
            }
            pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
                let mut decoder = crate::codec::Decoder::new(bytes);
                Ok(Self { #(#request_decode,)* })
            }
        }

        impl crate::Request for #request_type {
            const SERVICE: crate::Uuid = super::SERVICE;
            const CID: u32 = #cid;
            const COMMAND_TYPE: crate::CommandType = #command_type;
            type Response = #response_type;

            fn encode(&self) -> alloc::vec::Vec<u8> {
                self.to_bytes()
            }

            fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
                Self::from_bytes(bytes)
            }
        }

        #[derive(Debug, Clone, PartialEq, Default)]
        pub struct #response_type { #(#response_members,)* }

        impl #response_type {
            pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
                let info = message.command_info()?;
                Self::from_bytes(info.information_buffer)
            }
            pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
                let mut decoder = crate::codec::Decoder::new(bytes);
                Ok(Self { #(#response_decode,)* })
            }
            pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
                let mut encoder = crate::codec::Encoder::new();
                #(#response_encode)*
                encoder.finish()
            }
        }

        impl crate::Response for #response_type {
            type Request = #request_type;

            fn encode(&self) -> alloc::vec::Vec<u8> {
                self.to_bytes()
            }

            fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
                Self::from_bytes(bytes)
            }
        }
    }
}

fn fields_tokens(fields: &[Field]) -> Vec<proc_macro2::TokenStream> {
    fields
        .iter()
        .map(|field| {
            let ident = &field.ident;
            let ty = field_type(field, true);
            quote! { pub #ident: #ty }
        })
        .collect()
}

fn field_type(field: &Field, relative: bool) -> proc_macro2::TokenStream {
    match field.format.as_str() {
        "guint16" | "gint16" => quote! { u16 },
        "guint32" | "gint32" | "enum" | "flags" => quote! { u32 },
        "gint32-signed" => quote! { i32 },
        "guint64" => quote! { u64 },
        "uuid" => quote! { crate::Uuid },
        "ipv4" => quote! { [u8; 4] },
        "ipv6" => quote! { [u8; 16] },
        "ipv4-array" => quote! { alloc::vec::Vec<[u8; 4]> },
        "ipv6-array" => quote! { alloc::vec::Vec<[u8; 16]> },
        "string" => quote! { alloc::string::String },
        "string-array" => quote! { alloc::vec::Vec<alloc::string::String> },
        "guint32-array" => quote! { alloc::vec::Vec<u32> },
        "byte-array" | "ref-byte-array" | "uicc-ref-byte-array" | "unsized-byte-array" | "raw" => {
            quote! { alloc::vec::Vec<u8> }
        }
        "struct" | "ref-struct" | "struct-array" | "ref-struct-array" => {
            if let Some(ty) = &field.struct_type {
                let ty = if relative {
                    quote! { super::#ty }
                } else {
                    quote! { #ty }
                };
                if field.format.contains("array") {
                    quote! { alloc::vec::Vec<#ty> }
                } else {
                    quote! { #ty }
                }
            } else {
                quote! { alloc::vec::Vec<u8> }
            }
        }
        _ => quote! { alloc::vec::Vec<u8> },
    }
}

fn encode_field(field: &Field, owned_encoder: bool) -> proc_macro2::TokenStream {
    let ident = &field.ident;
    let nested_encoder = if owned_encoder {
        quote! { &mut encoder }
    } else {
        quote! { encoder }
    };
    match field.format.as_str() {
        "guint16" | "gint16" => quote! { encoder.write_u16(self.#ident); },
        "guint32" | "gint32" | "enum" | "flags" | "gint32-signed" => {
            quote! { encoder.write_u32(self.#ident as u32); }
        }
        "guint64" => quote! { encoder.write_u64(self.#ident); },
        "uuid" => quote! { encoder.write_bytes(&self.#ident.0); },
        "ipv4" | "ipv6" => quote! { encoder.write_bytes(&self.#ident); },
        "string" => {
            let utf8 = field.utf8;
            quote! { encoder.write_string(&self.#ident, #utf8); }
        }
        "string-array" => {
            let utf8 = field.utf8;
            quote! { encoder.write_string_array(&self.#ident, #utf8); }
        }
        "guint32-array" => quote! { for value in &self.#ident { encoder.write_u32(*value); } },
        "struct" | "ref-struct" => quote! { self.#ident.encode_to(#nested_encoder); },
        "struct-array" | "ref-struct-array" => {
            quote! { for value in &self.#ident { value.encode_to(#nested_encoder); } }
        }
        "ipv4-array" | "ipv6-array" => {
            quote! { for value in &self.#ident { encoder.write_bytes(value); } }
        }
        // UICC reference byte arrays store `[length][offset]`, the other way
        // round from every other reference (libmbim's `swapped_offset_length`).
        "uicc-ref-byte-array" => quote! { encoder.write_ref_swapped(&self.#ident); },
        _ => quote! { encoder.write_ref(&self.#ident); },
    }
}

fn decode_field(field: &Field, relative: bool, owned_decoder: bool) -> proc_macro2::TokenStream {
    let ident = &field.ident;
    let value = match field.format.as_str() {
        "guint16" | "gint16" => quote! { decoder.read_u16()? },
        "guint32" | "gint32" | "enum" | "flags" | "gint32-signed" => quote! { decoder.read_u32()? },
        "guint64" => quote! { decoder.read_u64()? },
        "uuid" => {
            quote! { crate::Uuid(decoder.read_bytes(16)?.try_into().map_err(|_| crate::Error::InvalidLength)?) }
        }
        "ipv4" => {
            quote! { decoder.read_bytes(4)?.try_into().map_err(|_| crate::Error::InvalidLength)? }
        }
        "ipv6" => {
            quote! { decoder.read_bytes(16)?.try_into().map_err(|_| crate::Error::InvalidLength)? }
        }
        "ipv4-array" => quote! { alloc::vec::Vec::new() },
        "ipv6-array" => quote! { alloc::vec::Vec::new() },
        "string" => {
            let utf8 = field.utf8;
            quote! { decoder.read_string(#utf8)? }
        }
        "guint32-array" => quote! { alloc::vec::Vec::new() },
        "string-array" => quote! { alloc::vec::Vec::new() },
        "struct" | "ref-struct" => {
            if let Some(ty) = &field.struct_type {
                if relative && owned_decoder {
                    quote! { super::#ty::decode_from(&mut decoder)? }
                } else if relative {
                    quote! { super::#ty::decode_from(decoder)? }
                } else {
                    quote! { #ty::decode_from(decoder)? }
                }
            } else {
                quote! { alloc::vec::Vec::new() }
            }
        }
        "struct-array" | "ref-struct-array" => quote! { alloc::vec::Vec::new() },
        "uicc-ref-byte-array" => quote! { decoder.read_ref_swapped()?.to_vec() },
        _ => quote! { decoder.read_ref()?.to_vec() },
    };
    quote! { #ident: #value }
}

fn type_ident(value: &str) -> Ident {
    let cleaned = value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>();
    format_ident!(
        "{}",
        if cleaned.is_empty() {
            "Generated"
        } else {
            &cleaned
        }
    )
}

fn field_ident(value: &str) -> Ident {
    let mut name = String::new();
    let characters = value.chars().collect::<Vec<_>>();
    for (index, character) in characters.iter().enumerate() {
        if !character.is_ascii_alphanumeric() {
            if !name.ends_with('_') {
                name.push('_');
            }
            continue;
        }
        let previous = index.checked_sub(1).and_then(|index| characters.get(index));
        let next = characters.get(index + 1);
        let boundary = character.is_ascii_uppercase()
            && index != 0
            && (previous.is_some_and(|previous| {
                previous.is_ascii_lowercase() || previous.is_ascii_digit()
            }) || (previous.is_some_and(|previous| previous.is_ascii_uppercase())
                && next.is_some_and(|next| next.is_ascii_lowercase())));
        if boundary && !name.ends_with('_') {
            name.push('_');
        }
        name.push(character.to_ascii_lowercase());
    }
    name = name.replace("i_pv", "ipv");
    if name.is_empty() {
        name.push_str("field");
    }
    if matches!(
        name.as_str(),
        "type" | "match" | "ref" | "self" | "crate" | "mod" | "move" | "async" | "loop" | "where"
    ) {
        name.push('_');
    }
    format_ident!("{}", name)
}

fn snake_ident(value: &str) -> Ident {
    let mut name = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_uppercase() && index != 0 {
            name.push('_');
        }
        name.push(character.to_ascii_lowercase());
    }
    format_ident!("{}", if name.is_empty() { "command" } else { &name })
}

fn uuid_tokens(uuid: &str) -> proc_macro2::TokenStream {
    let bytes = uuid
        .split('-')
        .flat_map(|part| {
            (0..part.len())
                .step_by(2)
                .map(move |index| u8::from_str_radix(&part[index..index + 2], 16).unwrap())
        })
        .collect::<Vec<_>>();
    quote! { crate::Uuid([#(#bytes),*]) }
}

fn find_service_uuid(name: &str) -> String {
    let known: HashMap<&str, &str> = [
        ("Basic Connect", "a289cc33-bcbb-8b4f-b6b0-133ec2aae6df"),
        ("SMS", "533fbeeb-14fe-4467-9eff-33a223e56c3f"),
        ("USSD", "e550a0c8-5e82-479e-82f7-10abf4c3351f"),
        ("Phonebook", "4bf38476-1e6a-41db-b1d8-bed289c25bdb"),
        ("STK", "d8f20131-fcb5-4e17-8602-d6ed3816164c"),
        ("Auth", "1d2b5ff7-0aa1-48b2-aa52-50f15767174e"),
        ("DSS", "c08a26dd-7718-4382-8482-6e0d583c4d0e"),
        ("MS Firmware ID", "e9f7dea2-feaf-4009-93ce-90a3694103b6"),
        ("MS Host Shutdown", "883b7c26-985f-43fa-9804-27d7fb80959c"),
        ("MS SAR", "68223d04-9f6c-4e0f-822d-28441fb72340"),
        ("Proxy Control", "838cf7fb-8d0d-4d7f-871e-d71dbefbb39b"),
        ("QMI", "d1a30bc2-f97a-6e43-bf65-c7e24fb0f0d3"),
        ("ATDS", "5967bdcc-7fd2-49a2-9f5c-b2e70e527db3"),
        (
            "Intel Firmware Update",
            "0ed374cb-f835-4474-bc11-3b3fd76f5641",
        ),
        (
            "Intel Firmware Update V2",
            "0ed374cb-f835-4474-bc11-3b3fd76f5641",
        ),
        ("QDU", "6427015f-579d-48f5-8c54-f43ed1e76f83"),
        (
            "Ms Basic Connect Extensions",
            "3d01dcc5-fef5-4d05-0d3a-bef7058e9aaf",
        ),
        (
            "Ms Basic Connect Extensions V2",
            "3d01dcc5-fef5-4d05-0d3a-bef7058e9aaf",
        ),
        (
            "Ms Basic Connect Extensions V3",
            "3d01dcc5-fef5-4d05-0d3a-bef7058e9aaf",
        ),
        (
            "Ms Basic Connect V2",
            "a289cc33-bcbb-8b4f-b6b0-133ec2aae6df",
        ),
        (
            "Ms Basic Connect V3",
            "a289cc33-bcbb-8b4f-b6b0-133ec2aae6df",
        ),
        (
            "MS UICC Low Level Access",
            "c2f6588e-f037-4bc9-8665-f4d44bd09367",
        ),
        ("Quectel", "11223344-5566-7788-99aa-bbccddeeff11"),
        ("Intel Thermal RF", "fdc22af2-f441-4d46-af8d-259fcdde4635"),
        (
            "MS Voice Extensions",
            "8d8b9eba-37be-449b-8f1e-61cb034a702e",
        ),
        (
            "Intel Mutual Authentication",
            "f85d46ef-ab26-4081-9868-4d183c0a3aec",
        ),
        ("Intel Tools", "4ada4962-b988-46c3-87a7-97f20f994abb"),
        ("Google", "3e1e92cf-c53d-4f14-85d0-a86ad9e12245"),
        ("Fibocom", "ffffffff-abca-4b11-a4e2-f2fc87f94488"),
        ("Compal", "a2a32a97-cab1-4f57-9ae1-451c74dda957"),
        ("Intel AT Tunnel", "da138c64-6515-4893-92b2-a1e1ca7c81ca"),
    ]
    .into_iter()
    .collect();
    known
        .get(name)
        .copied()
        .unwrap_or("00000000-0000-0000-0000-000000000000")
        .to_owned()
}

fn strip_comments(source: &str) -> String {
    source
        .lines()
        .map(|line| line.split_once("//").map(|(head, _)| head).unwrap_or(line))
        .collect::<Vec<_>>()
        .join("\n")
}
