#![no_std]

//! A small, transport-agnostic MBIM codec and client.
//!
//! The wire format follows the generic MBIM message and fragment layouts used
//! by Microsoft's CDC MBIM specification and by libmbim. USB WDM transport is
//! supplied by `rm-cdc-wdm`; this crate only knows how to encode, decode and
//! match MBIM messages.
//!
//! The per-service command and struct types under [`types`] are generated by
//! `cargo xtask mbim-codegen` from the libmbim service database in
//! `libmbim/data`.
//!
//! Commands are sent from the [`Session`] that [`MbimClient::with_session`]
//! hands out, with one of the generated request types: the [`Request`] trait
//! that request implements carries the service, the command id and the
//! response type, and its response points back at it.

extern crate alloc;

mod client;
pub mod codec;
mod command;
mod discovery;
mod error;
mod message;
pub mod types;

/// Metadata emitted for every command in the libmbim service database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CommandSpec {
    pub name: &'static str,
    pub cid: u32,
    pub query: bool,
    pub set: bool,
    pub response: bool,
}

pub use client::{Error as ClientError, MbimClient, Session};
pub use command::{Request, Response};
pub use discovery::{InterfaceSummary, find_mbim_interface, is_mbim_device};
pub use error::Error;
pub use message::{CommandInfo, CommandType, Message, MessageType, Uuid};
