//! Generated by `cargo xtask mbim-codegen`; do not edit.
//!
//! Source: `mbim-service-atds.json`.

#![allow(unused_imports, unused_mut, unused_variables)]
pub const SERVICE: crate::Uuid = crate::Uuid([
    89u8, 103u8, 189u8, 204u8, 127u8, 210u8, 73u8, 162u8, 159u8, 92u8, 178u8, 231u8, 14u8, 82u8,
    125u8, 179u8,
]);
pub const SERVICE_NAME: &str = "ATDS";
pub mod cid {
    pub const SIGNAL: u32 = 1u32;
    pub const LOCATION: u32 = 2u32;
    pub const OPERATORS: u32 = 3u32;
    pub const R_A_T: u32 = 4u32;
    pub const REGISTER_STATE: u32 = 5u32;
}
pub const COMMANDS: &[crate::CommandSpec] = &[
    crate::CommandSpec {
        name: "Signal",
        cid: 1u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Location",
        cid: 2u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Operators",
        cid: 3u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "RAT",
        cid: 4u32,
        query: true,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "RegisterState",
        cid: 5u32,
        query: true,
        set: false,
        response: true,
    },
];
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimAtdsProvider {
    pub provider_id: alloc::string::String,
    pub provider_state: u32,
    pub provider_name: alloc::string::String,
    pub plmn_mode: u32,
    pub rssi: u32,
    pub error_rate: u32,
}
impl MbimAtdsProvider {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_string(&self.provider_id, false);
        encoder.write_u32(self.provider_state as u32);
        encoder.write_string(&self.provider_name, false);
        encoder.write_u32(self.plmn_mode as u32);
        encoder.write_u32(self.rssi as u32);
        encoder.write_u32(self.error_rate as u32);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            provider_id: decoder.read_string(false)?,
            provider_state: decoder.read_u32()?,
            provider_name: decoder.read_string(false)?,
            plmn_mode: decoder.read_u32()?,
            rssi: decoder.read_u32()?,
            error_rate: decoder.read_u32()?,
        })
    }
}
pub mod signal {
    pub const CID: u32 = 1u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub rssi: u32,
        pub error_rate: u32,
        pub rscp: u32,
        pub ecno: u32,
        pub rsrq: u32,
        pub rsrp: u32,
        pub rssnr: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                rssi: decoder.read_u32()?,
                error_rate: decoder.read_u32()?,
                rscp: decoder.read_u32()?,
                ecno: decoder.read_u32()?,
                rsrq: decoder.read_u32()?,
                rsrp: decoder.read_u32()?,
                rssnr: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.rssi as u32);
            encoder.write_u32(self.error_rate as u32);
            encoder.write_u32(self.rscp as u32);
            encoder.write_u32(self.ecno as u32);
            encoder.write_u32(self.rsrq as u32);
            encoder.write_u32(self.rsrp as u32);
            encoder.write_u32(self.rssnr as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod location {
    pub const CID: u32 = 2u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 2u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub lac: u32,
        pub tac: u32,
        pub cell_id: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                lac: decoder.read_u32()?,
                tac: decoder.read_u32()?,
                cell_id: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.lac as u32);
            encoder.write_u32(self.tac as u32);
            encoder.write_u32(self.cell_id as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod operators {
    pub const CID: u32 = 3u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub providers_count: u32,
        pub providers: alloc::vec::Vec<super::MbimAtdsProvider>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                providers_count: decoder.read_u32()?,
                providers: alloc::vec::Vec::new(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.providers_count as u32);
            for value in &self.providers {
                value.encode_to(&mut encoder);
            }
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod r_a_t {
    pub const CID: u32 = 4u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 4u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub mode: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                mode: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.mode as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub mode: u32,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.mode as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                mode: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 4u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub mode: u32,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                mode: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.mode as u32);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod register_state {
    pub const CID: u32 = 5u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 5u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub nw_error: u32,
        pub register_state: u32,
        pub register_mode: u32,
        pub available_data_classes: u32,
        pub current_cellular_class: u32,
        pub provider_id: alloc::string::String,
        pub provider_name: alloc::string::String,
        pub roaming_text: alloc::string::String,
        pub registration_flag: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                nw_error: decoder.read_u32()?,
                register_state: decoder.read_u32()?,
                register_mode: decoder.read_u32()?,
                available_data_classes: decoder.read_u32()?,
                current_cellular_class: decoder.read_u32()?,
                provider_id: decoder.read_string(false)?,
                provider_name: decoder.read_string(false)?,
                roaming_text: decoder.read_string(false)?,
                registration_flag: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.nw_error as u32);
            encoder.write_u32(self.register_state as u32);
            encoder.write_u32(self.register_mode as u32);
            encoder.write_u32(self.available_data_classes as u32);
            encoder.write_u32(self.current_cellular_class as u32);
            encoder.write_string(&self.provider_id, false);
            encoder.write_string(&self.provider_name, false);
            encoder.write_string(&self.roaming_text, false);
            encoder.write_u32(self.registration_flag as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
