//! Generated by `cargo xtask mbim-codegen`; do not edit.
//!
//! Source: `mbim-service-auth.json`.

#![allow(unused_imports, unused_mut, unused_variables)]
pub const SERVICE: crate::Uuid = crate::Uuid([
    29u8, 43u8, 95u8, 247u8, 10u8, 161u8, 72u8, 178u8, 170u8, 82u8, 80u8, 241u8, 87u8, 103u8, 23u8,
    78u8,
]);
pub const SERVICE_NAME: &str = "Auth";
pub mod cid {
    pub const AKA: u32 = 1u32;
    pub const AKAP: u32 = 2u32;
    pub const SIM: u32 = 3u32;
}
pub const COMMANDS: &[crate::CommandSpec] = &[
    crate::CommandSpec {
        name: "Aka",
        cid: 1u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Akap",
        cid: 2u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Sim",
        cid: 3u32,
        query: true,
        set: false,
        response: true,
    },
];
pub mod aka {
    pub const CID: u32 = 1u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {
        pub rand: alloc::vec::Vec<u8>,
        pub autn: alloc::vec::Vec<u8>,
    }
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.rand);
            encoder.write_ref(&self.autn);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                rand: decoder.read_ref()?.to_vec(),
                autn: decoder.read_ref()?.to_vec(),
            })
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub res: alloc::vec::Vec<u8>,
        pub res_len: u32,
        pub integrating_key: alloc::vec::Vec<u8>,
        pub ciphering_key: alloc::vec::Vec<u8>,
        pub auts: alloc::vec::Vec<u8>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                res: decoder.read_ref()?.to_vec(),
                res_len: decoder.read_u32()?,
                integrating_key: decoder.read_ref()?.to_vec(),
                ciphering_key: decoder.read_ref()?.to_vec(),
                auts: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.res);
            encoder.write_u32(self.res_len as u32);
            encoder.write_ref(&self.integrating_key);
            encoder.write_ref(&self.ciphering_key);
            encoder.write_ref(&self.auts);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod akap {
    pub const CID: u32 = 2u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {
        pub rand: alloc::vec::Vec<u8>,
        pub autn: alloc::vec::Vec<u8>,
        pub network_name: alloc::string::String,
    }
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.rand);
            encoder.write_ref(&self.autn);
            encoder.write_string(&self.network_name, false);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                rand: decoder.read_ref()?.to_vec(),
                autn: decoder.read_ref()?.to_vec(),
                network_name: decoder.read_string(false)?,
            })
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 2u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub res: alloc::vec::Vec<u8>,
        pub res_len: u32,
        pub integrating_key: alloc::vec::Vec<u8>,
        pub ciphering_key: alloc::vec::Vec<u8>,
        pub auts: alloc::vec::Vec<u8>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                res: decoder.read_ref()?.to_vec(),
                res_len: decoder.read_u32()?,
                integrating_key: decoder.read_ref()?.to_vec(),
                ciphering_key: decoder.read_ref()?.to_vec(),
                auts: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.res);
            encoder.write_u32(self.res_len as u32);
            encoder.write_ref(&self.integrating_key);
            encoder.write_ref(&self.ciphering_key);
            encoder.write_ref(&self.auts);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod sim {
    pub const CID: u32 = 3u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {
        pub rand1: alloc::vec::Vec<u8>,
        pub rand2: alloc::vec::Vec<u8>,
        pub rand3: alloc::vec::Vec<u8>,
        pub n: u32,
    }
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.rand1);
            encoder.write_ref(&self.rand2);
            encoder.write_ref(&self.rand3);
            encoder.write_u32(self.n as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                rand1: decoder.read_ref()?.to_vec(),
                rand2: decoder.read_ref()?.to_vec(),
                rand3: decoder.read_ref()?.to_vec(),
                n: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub sres1: u32,
        pub kc1: u64,
        pub sres2: u32,
        pub kc2: u64,
        pub sres3: u32,
        pub kc3: u64,
        pub n: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                sres1: decoder.read_u32()?,
                kc1: decoder.read_u64()?,
                sres2: decoder.read_u32()?,
                kc2: decoder.read_u64()?,
                sres3: decoder.read_u32()?,
                kc3: decoder.read_u64()?,
                n: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.sres1 as u32);
            encoder.write_u64(self.kc1);
            encoder.write_u32(self.sres2 as u32);
            encoder.write_u64(self.kc2);
            encoder.write_u32(self.sres3 as u32);
            encoder.write_u64(self.kc3);
            encoder.write_u32(self.n as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
