//! Generated by `cargo xtask mbim-codegen`; do not edit.
//!
//! Source: `mbim-service-phonebook.json`.

#![allow(unused_imports, unused_mut, unused_variables)]
pub const SERVICE: crate::Uuid = crate::Uuid([
    75u8, 243u8, 132u8, 118u8, 30u8, 106u8, 65u8, 219u8, 177u8, 216u8, 190u8, 210u8, 137u8, 194u8,
    91u8, 219u8,
]);
pub const SERVICE_NAME: &str = "Phonebook";
pub mod cid {
    pub const CONFIGURATION: u32 = 1u32;
    pub const READ: u32 = 2u32;
    pub const DELETE: u32 = 3u32;
    pub const WRITE: u32 = 4u32;
}
pub const COMMANDS: &[crate::CommandSpec] = &[
    crate::CommandSpec {
        name: "Configuration",
        cid: 1u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Read",
        cid: 2u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Delete",
        cid: 3u32,
        query: false,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "Write",
        cid: 4u32,
        query: false,
        set: true,
        response: true,
    },
];
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimPhonebookEntry {
    pub entry_index: u32,
    pub number: alloc::string::String,
    pub name: alloc::string::String,
}
impl MbimPhonebookEntry {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_u32(self.entry_index as u32);
        encoder.write_string(&self.number, false);
        encoder.write_string(&self.name, false);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            entry_index: decoder.read_u32()?,
            number: decoder.read_string(false)?,
            name: decoder.read_string(false)?,
        })
    }
}
pub mod configuration {
    pub const CID: u32 = 1u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub state: u32,
        pub number_of_entries: u32,
        pub used_entries: u32,
        pub max_number_length: u32,
        pub max_name: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                state: decoder.read_u32()?,
                number_of_entries: decoder.read_u32()?,
                used_entries: decoder.read_u32()?,
                max_number_length: decoder.read_u32()?,
                max_name: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.state as u32);
            encoder.write_u32(self.number_of_entries as u32);
            encoder.write_u32(self.used_entries as u32);
            encoder.write_u32(self.max_number_length as u32);
            encoder.write_u32(self.max_name as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct Indication {
        pub state: u32,
        pub number_of_entries: u32,
        pub used_entries: u32,
        pub max_number_length: u32,
        pub max_name: u32,
    }
    impl Indication {
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                state: decoder.read_u32()?,
                number_of_entries: decoder.read_u32()?,
                used_entries: decoder.read_u32()?,
                max_number_length: decoder.read_u32()?,
                max_name: decoder.read_u32()?,
            })
        }
    }
}
pub mod read {
    pub const CID: u32 = 2u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {
        pub filter_flag: u32,
        pub filter_message_index: u32,
    }
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.filter_flag as u32);
            encoder.write_u32(self.filter_message_index as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                filter_flag: decoder.read_u32()?,
                filter_message_index: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 2u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub entry_count: u32,
        pub entries: alloc::vec::Vec<super::MbimPhonebookEntry>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                entry_count: decoder.read_u32()?,
                entries: alloc::vec::Vec::new(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.entry_count as u32);
            for value in &self.entries {
                value.encode_to(&mut encoder);
            }
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod delete {
    pub const CID: u32 = 3u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub filter_flag: u32,
        pub filter_message_index: u32,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.filter_flag as u32);
            encoder.write_u32(self.filter_message_index as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                filter_flag: decoder.read_u32()?,
                filter_message_index: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {}
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod write {
    pub const CID: u32 = 4u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub save_flag: u32,
        pub save_index: u32,
        pub number: alloc::string::String,
        pub name: alloc::string::String,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.save_flag as u32);
            encoder.write_u32(self.save_index as u32);
            encoder.write_string(&self.number, false);
            encoder.write_string(&self.name, false);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                save_flag: decoder.read_u32()?,
                save_index: decoder.read_u32()?,
                number: decoder.read_string(false)?,
                name: decoder.read_string(false)?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 4u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {}
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
