//! Generated by `cargo xtask mbim-codegen`; do not edit.
//!
//! Source: `mbim-service-sms.json`.

#![allow(unused_imports, unused_mut, unused_variables)]
pub const SERVICE: crate::Uuid = crate::Uuid([
    83u8, 63u8, 190u8, 235u8, 20u8, 254u8, 68u8, 103u8, 158u8, 255u8, 51u8, 162u8, 35u8, 229u8,
    108u8, 63u8,
]);
pub const SERVICE_NAME: &str = "SMS";
pub mod cid {
    pub const CONFIGURATION: u32 = 1u32;
    pub const READ: u32 = 2u32;
    pub const SEND: u32 = 3u32;
    pub const DELETE: u32 = 4u32;
    pub const MESSAGE_STORE_STATUS: u32 = 5u32;
}
pub const COMMANDS: &[crate::CommandSpec] = &[
    crate::CommandSpec {
        name: "Configuration",
        cid: 1u32,
        query: true,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "Read",
        cid: 2u32,
        query: true,
        set: false,
        response: true,
    },
    crate::CommandSpec {
        name: "Send",
        cid: 3u32,
        query: false,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "Delete",
        cid: 4u32,
        query: false,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "MessageStoreStatus",
        cid: 5u32,
        query: true,
        set: false,
        response: true,
    },
];
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimSmsPduReadRecord {
    pub message_index: u32,
    pub message_status: u32,
    pub pdu_data: alloc::vec::Vec<u8>,
}
impl MbimSmsPduReadRecord {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_u32(self.message_index as u32);
        encoder.write_u32(self.message_status as u32);
        encoder.write_ref(&self.pdu_data);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            message_index: decoder.read_u32()?,
            message_status: decoder.read_u32()?,
            pdu_data: decoder.read_ref()?.to_vec(),
        })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimSmsCdmaReadRecord {
    pub message_index: u32,
    pub message_status: u32,
    pub address: alloc::string::String,
    pub timestamp: alloc::string::String,
    pub encoding: u32,
    pub language: u32,
    pub encoded_message: alloc::vec::Vec<u8>,
    pub encoded_message_size_in_characters: u32,
}
impl MbimSmsCdmaReadRecord {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_u32(self.message_index as u32);
        encoder.write_u32(self.message_status as u32);
        encoder.write_string(&self.address, false);
        encoder.write_string(&self.timestamp, false);
        encoder.write_u32(self.encoding as u32);
        encoder.write_u32(self.language as u32);
        encoder.write_ref(&self.encoded_message);
        encoder.write_u32(self.encoded_message_size_in_characters as u32);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            message_index: decoder.read_u32()?,
            message_status: decoder.read_u32()?,
            address: decoder.read_string(false)?,
            timestamp: decoder.read_string(false)?,
            encoding: decoder.read_u32()?,
            language: decoder.read_u32()?,
            encoded_message: decoder.read_ref()?.to_vec(),
            encoded_message_size_in_characters: decoder.read_u32()?,
        })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimSmsPduSendRecord {
    pub pdu_data: alloc::vec::Vec<u8>,
}
impl MbimSmsPduSendRecord {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_ref(&self.pdu_data);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            pdu_data: decoder.read_ref()?.to_vec(),
        })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MbimSmsCdmaSendRecord {
    pub encoding: u32,
    pub language: u32,
    pub address: alloc::string::String,
    pub encoded_message: alloc::vec::Vec<u8>,
    pub encoded_message_size_in_characters: u32,
}
impl MbimSmsCdmaSendRecord {
    pub fn encode_to(&self, encoder: &mut crate::codec::Encoder) {
        encoder.write_u32(self.encoding as u32);
        encoder.write_u32(self.language as u32);
        encoder.write_string(&self.address, false);
        encoder.write_ref(&self.encoded_message);
        encoder.write_u32(self.encoded_message_size_in_characters as u32);
    }
    pub fn decode_from(decoder: &mut crate::codec::Decoder<'_>) -> Result<Self, crate::Error> {
        Ok(Self {
            encoding: decoder.read_u32()?,
            language: decoder.read_u32()?,
            address: decoder.read_string(false)?,
            encoded_message: decoder.read_ref()?.to_vec(),
            encoded_message_size_in_characters: decoder.read_u32()?,
        })
    }
}
pub mod configuration {
    pub const CID: u32 = 1u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub sms_storage_state: u32,
        pub format: u32,
        pub max_messages: u32,
        pub cdma_short_message_size: u32,
        pub sc_address: alloc::string::String,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                sms_storage_state: decoder.read_u32()?,
                format: decoder.read_u32()?,
                max_messages: decoder.read_u32()?,
                cdma_short_message_size: decoder.read_u32()?,
                sc_address: decoder.read_string(false)?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.sms_storage_state as u32);
            encoder.write_u32(self.format as u32);
            encoder.write_u32(self.max_messages as u32);
            encoder.write_u32(self.cdma_short_message_size as u32);
            encoder.write_string(&self.sc_address, false);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub format: u32,
        pub sc_address: alloc::string::String,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.format as u32);
            encoder.write_string(&self.sc_address, false);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                format: decoder.read_u32()?,
                sc_address: decoder.read_string(false)?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub sms_storage_state: u32,
        pub format: u32,
        pub max_messages: u32,
        pub cdma_short_message_size: u32,
        pub sc_address: alloc::string::String,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                sms_storage_state: decoder.read_u32()?,
                format: decoder.read_u32()?,
                max_messages: decoder.read_u32()?,
                cdma_short_message_size: decoder.read_u32()?,
                sc_address: decoder.read_string(false)?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.sms_storage_state as u32);
            encoder.write_u32(self.format as u32);
            encoder.write_u32(self.max_messages as u32);
            encoder.write_u32(self.cdma_short_message_size as u32);
            encoder.write_string(&self.sc_address, false);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct Indication {
        pub sms_storage_state: u32,
        pub format: u32,
        pub max_messages: u32,
        pub cdma_short_message_size: u32,
        pub sc_address: alloc::string::String,
    }
    impl Indication {
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                sms_storage_state: decoder.read_u32()?,
                format: decoder.read_u32()?,
                max_messages: decoder.read_u32()?,
                cdma_short_message_size: decoder.read_u32()?,
                sc_address: decoder.read_string(false)?,
            })
        }
    }
}
pub mod read {
    pub const CID: u32 = 2u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {
        pub format: u32,
        pub flag: u32,
        pub message_index: u32,
    }
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.format as u32);
            encoder.write_u32(self.flag as u32);
            encoder.write_u32(self.message_index as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                format: decoder.read_u32()?,
                flag: decoder.read_u32()?,
                message_index: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 2u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub format: u32,
        pub messages_count: u32,
        pub pdu_messages: alloc::vec::Vec<super::MbimSmsPduReadRecord>,
        pub cdma_messages: alloc::vec::Vec<super::MbimSmsCdmaReadRecord>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                format: decoder.read_u32()?,
                messages_count: decoder.read_u32()?,
                pdu_messages: alloc::vec::Vec::new(),
                cdma_messages: alloc::vec::Vec::new(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.format as u32);
            encoder.write_u32(self.messages_count as u32);
            for value in &self.pdu_messages {
                value.encode_to(&mut encoder);
            }
            for value in &self.cdma_messages {
                value.encode_to(&mut encoder);
            }
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct Indication {
        pub format: u32,
        pub messages_count: u32,
        pub pdu_messages: alloc::vec::Vec<super::MbimSmsPduReadRecord>,
        pub cdma_messages: alloc::vec::Vec<super::MbimSmsCdmaReadRecord>,
    }
    impl Indication {
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                format: decoder.read_u32()?,
                messages_count: decoder.read_u32()?,
                pdu_messages: alloc::vec::Vec::new(),
                cdma_messages: alloc::vec::Vec::new(),
            })
        }
    }
}
pub mod send {
    pub const CID: u32 = 3u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub format: u32,
        pub pdu_message: super::MbimSmsPduSendRecord,
        pub cdma_message: super::MbimSmsCdmaSendRecord,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.format as u32);
            self.pdu_message.encode_to(&mut encoder);
            self.cdma_message.encode_to(&mut encoder);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                format: decoder.read_u32()?,
                pdu_message: super::MbimSmsPduSendRecord::decode_from(&mut decoder)?,
                cdma_message: super::MbimSmsCdmaSendRecord::decode_from(&mut decoder)?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub message_reference: u32,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                message_reference: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.message_reference as u32);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod delete {
    pub const CID: u32 = 4u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub flag: u32,
        pub message_index: u32,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.flag as u32);
            encoder.write_u32(self.message_index as u32);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                flag: decoder.read_u32()?,
                message_index: decoder.read_u32()?,
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 4u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {}
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod message_store_status {
    pub const CID: u32 = 5u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 5u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub flag: u32,
        pub message_index: u32,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                flag: decoder.read_u32()?,
                message_index: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_u32(self.flag as u32);
            encoder.write_u32(self.message_index as u32);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct Indication {
        pub flag: u32,
        pub message_index: u32,
    }
    impl Indication {
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                flag: decoder.read_u32()?,
                message_index: decoder.read_u32()?,
            })
        }
    }
}
