//! Generated by `cargo xtask mbim-codegen`; do not edit.
//!
//! Source: `mbim-service-stk.json`.

#![allow(unused_imports, unused_mut, unused_variables)]
pub const SERVICE: crate::Uuid = crate::Uuid([
    216u8, 242u8, 1u8, 49u8, 252u8, 181u8, 78u8, 23u8, 134u8, 2u8, 214u8, 237u8, 56u8, 22u8, 22u8,
    76u8,
]);
pub const SERVICE_NAME: &str = "STK";
pub mod cid {
    pub const PAC: u32 = 1u32;
    pub const TERMINAL_RESPONSE: u32 = 2u32;
    pub const ENVELOPE: u32 = 3u32;
}
pub const COMMANDS: &[crate::CommandSpec] = &[
    crate::CommandSpec {
        name: "Pac",
        cid: 1u32,
        query: true,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "TerminalResponse",
        cid: 2u32,
        query: false,
        set: true,
        response: true,
    },
    crate::CommandSpec {
        name: "Envelope",
        cid: 3u32,
        query: true,
        set: true,
        response: true,
    },
];
pub mod pac {
    pub const CID: u32 = 1u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub pac_support: alloc::vec::Vec<u8>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                pac_support: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.pac_support);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub pac_host_control: alloc::vec::Vec<u8>,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.pac_host_control);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                pac_host_control: decoder.read_ref()?.to_vec(),
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 1u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub pac_support: alloc::vec::Vec<u8>,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                pac_support: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.pac_support);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct Indication {
        pub pac_type: u32,
        pub data_buffer: alloc::vec::Vec<u8>,
    }
    impl Indication {
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                pac_type: decoder.read_u32()?,
                data_buffer: decoder.read_ref()?.to_vec(),
            })
        }
    }
}
pub mod terminal_response {
    pub const CID: u32 = 2u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub response: alloc::vec::Vec<u8>,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.response);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                response: decoder.read_ref()?.to_vec(),
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 2u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub result_data: alloc::vec::Vec<u8>,
        pub status_words: u32,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                result_data: decoder.read_ref()?.to_vec(),
                status_words: decoder.read_u32()?,
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.result_data);
            encoder.write_u32(self.status_words as u32);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
pub mod envelope {
    pub const CID: u32 = 3u32;
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryRequest {}
    impl QueryRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {})
        }
    }
    impl crate::Request for QueryRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Query;
        type Response = QueryResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct QueryResponse {
        pub envelope_support: alloc::vec::Vec<u8>,
    }
    impl QueryResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                envelope_support: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.envelope_support);
            encoder.finish()
        }
    }
    impl crate::Response for QueryResponse {
        type Request = QueryRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetRequest {
        pub data: alloc::vec::Vec<u8>,
    }
    impl SetRequest {
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.data);
            encoder.finish()
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                data: decoder.read_ref()?.to_vec(),
            })
        }
    }
    impl crate::Request for SetRequest {
        const SERVICE: crate::Uuid = super::SERVICE;
        const CID: u32 = 3u32;
        const COMMAND_TYPE: crate::CommandType = crate::CommandType::Set;
        type Response = SetResponse;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct SetResponse {
        pub envelope_support: alloc::vec::Vec<u8>,
    }
    impl SetResponse {
        pub fn from_message(message: &crate::Message) -> Result<Self, crate::Error> {
            let info = message.command_info()?;
            Self::from_bytes(info.information_buffer)
        }
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, crate::Error> {
            let mut decoder = crate::codec::Decoder::new(bytes);
            Ok(Self {
                envelope_support: decoder.read_ref()?.to_vec(),
            })
        }
        pub fn to_bytes(&self) -> alloc::vec::Vec<u8> {
            let mut encoder = crate::codec::Encoder::new();
            encoder.write_ref(&self.envelope_support);
            encoder.finish()
        }
    }
    impl crate::Response for SetResponse {
        type Request = SetRequest;
        fn encode(&self) -> alloc::vec::Vec<u8> {
            self.to_bytes()
        }
        fn decode(bytes: &[u8]) -> Result<Self, crate::Error> {
            Self::from_bytes(bytes)
        }
    }
}
